import type { CouncilEvent } from './types';

export const historicalCouncilEvents: CouncilEvent[] = [
  {
    id: 'historical-britain-soe-rivalry',
    nationIds: ['britain'], historicalYear: 1942, category: '영국 · 정보기관', title: 'SOE·SIS·외무부의 작전선이 충돌했습니다',
    briefing: '점령 유럽의 한 조직을 두고 SOE는 파괴공작, SIS는 장기 정보수집, 외무부는 망명정부와의 정치 협의를 요구합니다.',
    stakes: '한 기관에 힘을 실으면 작전은 빨라지지만 다른 기관의 인재와 정보가 멀어질 수 있습니다.',
    historicalBasis: 'SOE는 경제전쟁부 아래에서 점령지 저항을 지원했고, SIS·외무부와 임무·통제를 둘러싼 긴장이 존재했습니다.',
    sourceLabel: '제국전쟁박물관 · SOE', sourceUrl: 'https://www.iwm.org.uk/history/soe-the-secret-british-organisation-of-the-second-world-war',
    choices: [
      { id: 'britain-soe-action', title: 'SOE에 공작 전권을 준다', description: '무전·폭파·현지훈련 예산을 한 지휘선으로 묶습니다.', result: '저항망은 빠르게 무장했지만 외교적 통제와 장기 정보의 정밀도가 낮아졌습니다.', effect: { gameDelta: { intelNetwork: 10, politicalPower: -6, enemyPressure: -3 }, careerReputation: 5 } },
      { id: 'britain-soe-joint', title: '합동통제실을 설치한다', description: 'SIS·SOE·외무부 연락관이 목표와 사후정치를 함께 승인합니다.', result: '속도는 느려졌지만 공작과 외교가 같은 전후 구상 아래 움직이기 시작했습니다.', effect: { gameDelta: { intelNetwork: 6, stability: 4 }, careerTrust: 7, relationChange: 4 } },
      { id: 'britain-soe-political', title: '망명정부 승인을 우선한다', description: '현지 정치 대표가 요청한 작전만 지원합니다.', result: '파괴공작 수는 줄었으나 점령지 세력의 정치적 신뢰와 전후 협력 기반이 커졌습니다.', effect: { relationChange: 9, gameDelta: { politicalPower: 7, enemyPressure: 2 } } },
    ],
  },
  {
    id: 'historical-usa-oss-foundation',
    nationIds: ['usa'], historicalYear: 1942, category: '미국 · 정보개편', title: '신설 OSS의 권한 경계를 정해야 합니다',
    briefing: '도노번은 해외정보·분석·특수작전을 한 기관에 모으려 하지만 육해군 정보부와 FBI가 자료와 관할을 지키려 합니다.',
    stakes: '통합 속도, 기관 간 견제, 현장 자율성 중 무엇을 택하느냐가 미국 정보체계의 미래를 바꿉니다.',
    historicalBasis: '전략정보국(OSS)은 1942년 6월 창설되어 연구분석과 해외 특수작전을 결합했으며 기존 기관과 관할 경쟁을 겪었습니다.',
    sourceLabel: 'CIA 박물관 · OSS', sourceUrl: 'https://www.cia.gov/legacy/museum/exhibit/the-office-of-strategic-services-n-americas-first-intelligence-agency/',
    choices: [
      { id: 'usa-oss-centralize', title: '도노번의 중앙집권안을 승인한다', description: '해외 비밀예산과 분석 인력을 OSS로 집중합니다.', result: '새 기관은 빠르게 성장했지만 군 정보부가 전구 자료 공유에 조건을 붙였습니다.', effect: { gameDelta: { intelNetwork: 12, commandPoints: -5, treasury: -90 }, careerReputation: 5 } },
      { id: 'usa-oss-board', title: '합동정보위원회 아래 둔다', description: '군·국무부·OSS가 공동 우선순위와 감사를 운영합니다.', result: '기관 독주는 막았지만 긴급 공작의 승인 시간이 길어졌습니다.', effect: { gameDelta: { intelNetwork: 7, politicalPower: 6 }, careerTrust: 7 } },
      { id: 'usa-oss-theater', title: '전구별 자율권을 보장한다', description: '유럽·중국·태평양 지부가 현지 사령관과 직접 협상합니다.', result: '현장 대응은 빨라졌으나 서로 다른 정보망과 교리가 생겨났습니다.', effect: { gameDelta: { intelNetwork: 9, commandPoints: 7, stability: -3 }, careerReputation: 3 } },
    ],
  },
  {
    id: 'historical-ussr-stavka-reserve',
    nationIds: ['ussr'], historicalYear: 1942, category: '소련 · 최고사령부', title: '스탈린그라드 축선의 전략예비대 배치를 결정하십시오',
    briefing: '전선군은 즉시 증원을 요구하지만 총참모부는 반격을 위해 기갑·포병 예비대를 숨겨 보존하자고 제안합니다.',
    stakes: '오늘의 방어선과 겨울 반격, 지휘관의 보고 자유가 동시에 걸려 있습니다.',
    historicalBasis: '1942년 스타프카와 총참모부는 남부 위기 속에서 전선 보강과 대규모 포위반격 준비를 병행했습니다.',
    sourceLabel: '미 육군 군사사센터 · 제2차대전사', sourceUrl: 'https://history.army.mil/Publications/Publications-Catalog/Publications-by-Number/',
    choices: [
      { id: 'ussr-reserve-front', title: '예비대를 즉시 전선에 넣는다', description: '도시와 도하점을 지키도록 모든 가용 전력을 분산 투입합니다.', result: '붕괴 직전의 부대가 버텼지만 결정적 반격의 충격력은 줄었습니다.', effect: { divisionOrganization: 10, divisionSupply: 6, gameDelta: { commandPoints: -8, enemyPressure: -4 } } },
      { id: 'ussr-reserve-mask', title: '반격집단을 은폐한다', description: '전선의 위험을 감수하고 기갑·포병을 후방 집결지에 보존합니다.', result: '손실 보고가 늘었지만 적이 알지 못하는 작전예비대가 완성됐습니다.', effect: { gameDelta: { enemyPressure: 6, commandPoints: 13, intelNetwork: 5 }, careerReputation: 6 } },
      { id: 'ussr-reserve-delegate', title: '전선군에 배분권을 넘긴다', description: '현지 지휘관들이 예비대의 투입 시점과 축선을 결정하게 합니다.', result: '현장 판단은 빨라졌고 지휘관 신뢰가 회복됐지만 중앙의 통제력은 약해졌습니다.', effect: { divisionOrganization: 6, careerTrust: 8, gameDelta: { politicalPower: -7, stability: 4 } } },
    ],
  },
  {
    id: 'historical-germany-resistance-orders',
    nationIds: ['germany'], historicalYear: 1942, category: '독일 · 명령과 저항', title: '중부집단군 참모들이 불법 명령 집행을 거부하려 합니다',
    briefing: '일부 장교가 민간인 보복과 무차별 처형 명령이 군 기강과 국가의 미래를 파괴한다며 기록·집행 방식을 바꾸자고 요구합니다.',
    stakes: '정권 충성, 장교단 결속, 점령지 저항과 향후 쿠데타 세력의 성장이 연결됩니다.',
    historicalBasis: '트레스코를 포함한 중부집단군의 반정권 장교들은 1942년 군부 저항망을 강화하고 정권 제거 구상을 발전시켰습니다.',
    sourceLabel: '독일 저항기념관 · 트레스코', sourceUrl: 'https://www.gdw-berlin.de/en/recess/biographies/index_of_persons/biographie/view-bio/henning-von-tresckow/',
    choices: [
      { id: 'germany-orders-refuse', title: '명령을 서면으로 거부한다', description: '군법·전쟁법 위반을 기록하고 예하부대에 집행 중지를 명령합니다.', result: '점령지 저항은 누그러졌지만 정권 기관이 지휘부의 충성을 조사하기 시작했습니다.', effect: { gameDelta: { stability: -5, enemyPressure: -8, warSupport: -3 }, careerReputation: 9 } },
      { id: 'germany-orders-delay', title: '현장에서 집행을 무력화한다', description: '보고 누락과 명령 재해석으로 피해를 줄이되 공개 충돌은 피합니다.', result: '당장의 숙청은 피했으나 비밀을 공유한 장교망이 별도의 권력 기반이 됐습니다.', effect: { gameDelta: { intelNetwork: 8, politicalPower: -4, enemyPressure: -4 }, careerTrust: 2 } },
      { id: 'germany-orders-enforce', title: '정권 명령을 그대로 집행한다', description: '저항 징후를 집단 처벌로 억누르고 보안기관과 협력합니다.', result: '단기 통제와 정권 신임은 높아졌지만 점령지 저항과 장교단의 도덕적 붕괴가 심화됐습니다.', effect: { enemyTerritorySupply: -7, careerTrust: 7, gameDelta: { enemyPressure: 10, stability: -7, warSupport: -5 } } },
    ],
  },
  {
    id: 'historical-japan-mobilization',
    nationIds: ['japan'], historicalYear: 1942, category: '일본 · 자원동원', title: '해상수송 감소로 1942년 물자동원계획이 흔들립니다',
    briefing: '기획원은 선박·연료·강철이 육군 점령지, 해군 함대, 본토 생산을 동시에 만족시킬 수 없다고 보고합니다.',
    stakes: '육해군의 경쟁을 누가 통제하는지에 따라 전선과 경제의 붕괴 시점이 달라집니다.',
    historicalBasis: '일본 기획원은 1942년 물자동원계획을 수립했지만 전황 악화와 해상수송력 감소로 계획 축소를 겪었습니다.',
    sourceLabel: '일본 국립국회도서관 · 국가총동원', sourceUrl: 'https://www.ndl.go.jp/modern/e/cha4/description19.html',
    choices: [
      { id: 'japan-mobilization-navy', title: '호송선단과 해군 연료를 우선한다', description: '신규 공세를 줄이고 유조선·수송선·해상호위를 보강합니다.', result: '해상 보급은 안정됐지만 육군의 전선 확대 요구가 좌절됐습니다.', effect: { divisionSupply: 7, gameDelta: { navalPower: 8, fuel: 12, warSupport: -4 } } },
      { id: 'japan-mobilization-army', title: '남방군의 현지조달을 확대한다', description: '점령지 자원과 노동을 육군이 직접 동원하게 합니다.', result: '전선 물자는 늘었지만 점령지 경제와 민심이 급속히 악화됐습니다.', effect: { productionEfficiency: 7, enemyTerritorySupply: -8, gameDelta: { enemyPressure: 9, stability: -5 } } },
      { id: 'japan-mobilization-board', title: '육해군 공동자원위원회를 강제한다', description: '기획원이 선박과 원료의 월별 배분표를 구속력 있게 집행합니다.', result: '일부 낭비가 줄었지만 육해군 모두 중앙 배분권에 반발했습니다.', effect: { productionEfficiency: 5, careerReputation: 7, careerTrust: -4, gameDelta: { politicalPower: 8 } } },
    ],
  },
  {
    id: 'historical-china-stilwell-command',
    nationIds: ['china'], historicalYear: 1942, category: '중국 · 연합지휘', title: '스틸웰의 지휘권과 중국군 통수권이 충돌했습니다',
    briefing: '미국 원조와 버마 작전을 책임진 스틸웰은 중국군 훈련·배치 권한을 요구하지만 국민정부 장성들은 국가 통수권 침해라고 반발합니다.',
    stakes: '원조의 규모, 중국군의 자율성, 지방군과 중앙군의 균형이 한 협정에 달렸습니다.',
    historicalBasis: '스틸웰은 1942년 중국전구 참모장과 미군 지휘관 역할을 동시에 맡았지만 실제 지휘권은 모호해 장제스와 갈등했습니다.',
    sourceLabel: '미 육군 군사사센터 · Stilwell’s Mission to China', sourceUrl: 'https://history.army.mil/Publications/Publications-Catalog/Stilwells-Mission-to-China/',
    choices: [
      { id: 'china-stilwell-command', title: '원조와 지휘권을 교환한다', description: '지정 부대를 연합훈련·작전 지휘 아래 두고 장비를 우선 배정받습니다.', result: '정예군의 전투력은 올랐지만 국내 장성들의 정치적 반발이 커졌습니다.', effect: { divisionOrganization: 9, productionEfficiency: 4, careerTrust: -6, gameDelta: { treasury: 120 } } },
      { id: 'china-stilwell-advisory', title: '참모권만 인정한다', description: '스틸웰은 계획과 훈련을 조언하되 최종 명령은 중국군 계통으로 내립니다.', result: '연합 협력은 느리지만 통수권과 장교단의 체면을 지켰습니다.', effect: { divisionOrganization: 5, careerTrust: 6, relationChange: 3, gameDelta: { commandPoints: 5 } } },
      { id: 'china-stilwell-regional', title: '버마군만 별도 통합한다', description: '해외 원정군은 연합지휘, 국내 전선은 중국군 지휘로 나눕니다.', result: '타협은 성립했지만 두 군의 장비·훈련 격차가 새로운 정치 문제가 됐습니다.', effect: { divisionSupply: 7, relationChange: 6, gameDelta: { stability: -3, factories: 1 } } },
    ],
  },
  {
    id: 'historical-india-quit-india',
    nationIds: ['india'], historicalYear: 1942, category: '인도 · 독립운동', title: 'Quit India 결의 뒤 전국 지도부가 체포됐습니다',
    briefing: '총독부는 전시 치안을 이유로 지도부 구금을 유지하려 하지만 지방 시위·파업·지하방송이 확산되고 인도군의 충성도도 시험받습니다.',
    stakes: '전시 동원과 즉각 독립, 종교·지역 대표권을 어떤 순서로 다룰지 결정해야 합니다.',
    historicalBasis: '인도국민회의는 1942년 8월 영국 철수를 요구했고 간디·아자드·네루 등 지도부는 곧 체포되었습니다.',
    sourceLabel: '영국 국립문서보관소 · Indian Independence', sourceUrl: 'https://www.nationalarchives.gov.uk/education/resources/indian-independence/',
    choices: [
      { id: 'india-quit-release', title: '지도부를 석방하고 협상한다', description: '전후 약속이 아닌 단계별 권력이양 일정을 제시합니다.', result: '대중 시위는 진정됐지만 총독부와 제국 강경파가 권한 상실을 경고했습니다.', effect: { gameDelta: { stability: 10, politicalPower: -10, warSupport: -3 }, careerReputation: 8 } },
      { id: 'india-quit-crackdown', title: '비상통치를 강화한다', description: '통신·철도·집회를 군정 아래 두고 지하조직을 체포합니다.', result: '주요 수송망은 회복됐지만 독립운동이 분산된 지하투쟁으로 바뀌었습니다.', effect: { divisionSupply: 8, gameDelta: { stability: -10, intelNetwork: 5, enemyPressure: 7 }, careerTrust: 5 } },
      { id: 'india-quit-convention', title: '전 인도 헌정회의를 소집한다', description: '국민회의·무슬림연맹·번왕국·소수집단에 별도 대표권을 줍니다.', result: '즉각 합의는 실패했지만 전후 국가구조를 둘러싼 협상이 제도 안으로 들어왔습니다.', effect: { relationChange: 8, gameDelta: { politicalPower: 10, stability: 4, treasury: -80 } } },
    ],
  },
  {
    id: 'historical-freefrance-unification',
    nationIds: ['freefrance'], historicalYear: 1942, category: '자유 프랑스 · 레지스탕스', title: '장 물랭이 국내 저항조직 통합안을 보내왔습니다',
    briefing: 'Combat·Libération-Sud·Franc-Tireur는 공동 비밀군에는 동의하지만 정치적 독립성과 런던의 명령권을 두고 이견을 보입니다.',
    stakes: '통합된 지휘, 운동별 자율성, 해방 뒤 공화국의 대표성이 함께 결정됩니다.',
    historicalBasis: '장 물랭은 1942년 남부 주요 운동을 조정하고 비밀군과 공동기관을 만드는 작업을 추진했습니다.',
    sourceLabel: '프랑스 국방부 · 레지스탕스 통합', sourceUrl: 'https://www.cheminsdememoire.gouv.fr/fr/lunification-de-la-resistance',
    choices: [
      { id: 'freefrance-unify-command', title: '비밀군 단일지휘를 강제한다', description: '무기와 무전 지원을 공동사령부 참여 조건으로 묶습니다.', result: '군사 행동은 정돈됐지만 일부 운동이 정치적 종속을 우려했습니다.', effect: { gameDelta: { intelNetwork: 10, commandPoints: 9, stability: -3 }, careerTrust: 4 } },
      { id: 'freefrance-unify-council', title: '정치평의회와 군사부를 분리한다', description: '운동 대표는 정치에, 델레스트랭의 비밀군은 작전에 집중합니다.', result: '복잡한 이중구조가 생겼지만 해방 뒤 대표성과 작전 전문성을 함께 지켰습니다.', effect: { gameDelta: { intelNetwork: 7, politicalPower: 9 }, careerReputation: 6, relationChange: 5 } },
      { id: 'freefrance-unify-network', title: '느슨한 지원연합으로 남긴다', description: '각 운동이 자체 조직을 유지하고 런던은 자금·무전만 배분합니다.', result: '현장 자율성은 높았지만 중복공작과 정보 누락이 이어졌습니다.', effect: { gameDelta: { intelNetwork: 5, enemyPressure: -4 }, relationChange: 7, careerTrust: -4 } },
    ],
  },
  {
    id: 'historical-italy-command-crisis',
    nationIds: ['italy'], historicalYear: 1942, category: '이탈리아 · 이중권력', title: '왕실·파시스트당·최고사령부가 패전 책임을 떠넘깁니다',
    briefing: '지중해 수송 손실과 동부전선 부담이 커지자 왕실 장성, 당 지도부, 독일 연락단이 서로 다른 철수·증원안을 제출했습니다.',
    stakes: '전선 보존뿐 아니라 향후 정권 교체와 휴전 협상의 주도권이 걸려 있습니다.',
    historicalBasis: '1942년 이탈리아 전쟁 수행은 왕국 제도, 무솔리니 정권, 군 최고사령부와 독일 동맹 사이의 분열된 권한 아래 진행되었습니다.',
    sourceLabel: '미 육군 군사사센터 · 지중해 전구사', sourceUrl: 'https://history.army.mil/Publications/Publications-Catalog/Europe-Mediterranean-Middle-East/',
    choices: [
      { id: 'italy-command-royal', title: '왕실 장성들에게 수습권을 준다', description: '전선 축소와 병력 귀환을 우선하고 당 조직을 군 지휘에서 배제합니다.', result: '부대 손실은 줄었지만 파시스트당이 왕실의 정권 장악을 의심하기 시작했습니다.', effect: { divisionSupply: 8, gameDelta: { enemyPressure: -5, stability: -4, warSupport: -5 }, careerReputation: 7 } },
      { id: 'italy-command-party', title: '정권의 총력전 노선을 따른다', description: '상징적 전선을 유지하고 당이 생산·선전을 직접 감독합니다.', result: '단기 전쟁 지지는 올랐지만 수송과 재정의 구조적 위기는 더 깊어졌습니다.', effect: { productionEfficiency: 6, careerTrust: 7, gameDelta: { warSupport: 7, treasury: -150, fuel: -10 } } },
      { id: 'italy-command-secret', title: '군 수습과 비밀외교를 병행한다', description: '공식 동맹을 유지하면서 중립국을 통해 출구 조건을 탐색합니다.', result: '전선 압력은 줄었지만 비밀을 아는 파벌들이 서로를 견제하기 시작했습니다.', effect: { gameDelta: { intelNetwork: 9, enemyPressure: -7, politicalPower: -6 }, relationChange: 5 } },
    ],
  },
  {
    id: 'historical-korea-kla-control',
    nationIds: ['korea'], historicalYear: 1942, category: '한국 · 망명군', title: '광복군 지휘권과 중국 측 통제조건을 재협상해야 합니다',
    briefing: '중국 전구는 작전·인사 통제를 원하고 임시정부는 독자 통수권과 연합국 승인을 요구합니다. 조선의용대 합류 인사들도 별도 정치 기반을 지킵니다.',
    stakes: '무기와 훈련을 얻는 속도, 독립군의 자율성, 해방 뒤 군 통합의 형태가 결정됩니다.',
    historicalBasis: '한국광복군은 중국에서 창설되어 중국 군사위원회의 통제 조건 아래 활동했고 1942년 조선의용대 일부가 합류했습니다.',
    sourceLabel: '국사편찬위원회 · 한국사데이터베이스', sourceUrl: 'https://db.history.go.kr/',
    choices: [
      { id: 'korea-kla-integrate', title: '연합훈련을 조건으로 통제를 수용한다', description: '중국 측 작전계통에 들어가 장비·교육·전구 이동권을 확보합니다.', result: '광복군의 실전 준비는 빨라졌지만 임시정부 내부에서 군사 자주권 논쟁이 커졌습니다.', effect: { divisionOrganization: 9, divisionSupply: 7, relationChange: 6, careerTrust: -4 } },
      { id: 'korea-kla-autonomy', title: '독자 통수권을 고수한다', description: '소규모라도 임시정부 직할 편제와 국내정진 계획을 유지합니다.', result: '장비는 부족했지만 군의 상징성과 해방 뒤 정통성은 강해졌습니다.', effect: { careerReputation: 9, gameDelta: { politicalPower: 9, factories: -1, warSupport: 5 } } },
      { id: 'korea-kla-coalition', title: '광복군·의용대 공동위원회를 만든다', description: '서로 다른 독립운동 계열에 인사·선전·작전 의석을 나눕니다.', result: '갈등은 남았지만 더 넓은 인재망과 국내 연락선이 하나의 계획표에 들어왔습니다.', effect: { gameDelta: { intelNetwork: 10, stability: 7, commandPoints: -3 }, careerTrust: 6 } },
    ],
  },
  {
    id: 'historical-vietnam-ho-detention',
    nationIds: ['vietnam'], historicalYear: 1942, category: '베트남 · 지도부 공백', title: '호찌민이 중국에서 구금되어 중앙 연락이 끊겼습니다',
    briefing: '국경 연락책은 석방 외교를, 국내 간부는 분산지도 체제를, 무장대는 즉각적인 근거지 확대를 요구합니다.',
    stakes: '지도자 구출과 조직 생존, 무장투쟁의 시기를 어떻게 배분할지 선택해야 합니다.',
    historicalBasis: '호찌민은 1942년 중국으로 이동하다 국민당 당국에 체포되어 1943년까지 여러 감옥에 구금되었습니다.',
    sourceLabel: '호찌민 박물관', sourceUrl: 'https://baotanghochiminh.vn/',
    choices: [
      { id: 'vietnam-detention-diplomacy', title: '중국 측 석방외교에 집중한다', description: '대외연락 인력과 자금을 지도자 신원 보증과 협상에 투입합니다.', result: '국제 연락은 개선됐지만 국내 무장조직의 보급이 늦어졌습니다.', effect: { relationChange: 9, careerTrust: 6, gameDelta: { politicalPower: -6, intelNetwork: 4 } } },
      { id: 'vietnam-detention-collective', title: '분산 중앙위원회를 가동한다', description: '정치·군사·재정 책임자가 합의제로 조직을 유지합니다.', result: '결정은 느려졌지만 체포 한 번에 조직 전체가 무너지지 않는 구조가 생겼습니다.', effect: { gameDelta: { stability: 8, intelNetwork: 8, commandPoints: -4 }, careerReputation: 5 } },
      { id: 'vietnam-detention-arms', title: '무장대 확대로 주도권을 만든다', description: '국경 근거지와 구국군에 인력·무기를 우선 배분합니다.', result: '현장 영향력은 커졌지만 조기 노출과 보복 작전의 위험도 높아졌습니다.', effect: { divisionOrganization: 8, careerReputation: 7, gameDelta: { enemyPressure: 9, warSupport: 6 } } },
    ],
  },
  {
    id: 'historical-indonesia-occupation-network',
    nationIds: ['indonesia'], historicalYear: 1942, category: '인도네시아 · 점령정치', title: '점령행정 참여와 지하저항 노선이 갈라졌습니다',
    briefing: '일부 지도자는 대중조직과 행정 공간을 이용하자고 하고, 샤리르 계열은 일본과의 협력을 거부한 비밀망을 만들자고 주장합니다.',
    stakes: '대중 동원력, 도덕적 정당성, 독립선언 시점과 점령군 감시가 서로 얽혀 있습니다.',
    historicalBasis: '1942년 일본 점령 뒤 수카르노·하타는 공개 정치공간을 활용했고 샤리르는 반일 지하망을 조직하는 등 독립운동 노선이 분화했습니다.',
    sourceLabel: '인도네시아 국가기록원', sourceUrl: 'https://anri.go.id/',
    choices: [
      { id: 'indonesia-network-public', title: '공개 대중조직에 들어간다', description: '교육·배급·노무 조직을 활용해 전국 단위 인맥을 확보합니다.', result: '대중 접촉은 크게 늘었지만 점령행정에 협력했다는 정치적 부채가 생겼습니다.', effect: { gameDelta: { manpower: 150, politicalPower: 10, stability: -4 }, careerReputation: -3 } },
      { id: 'indonesia-network-underground', title: '지하저항망을 우선한다', description: '청년·노동·학생 셀을 작게 나누고 공개 지도부와 거리를 둡니다.', result: '조직 규모는 작았지만 독립 시점에 쓸 수 있는 비밀 연락선이 살아남았습니다.', effect: { gameDelta: { intelNetwork: 12, enemyPressure: 5, politicalPower: -3 }, careerReputation: 6 } },
      { id: 'indonesia-network-dual', title: '공개·지하 이중구조를 만든다', description: '공개 지도부가 자원과 정보를 빼내 지하조직에 전달합니다.', result: '두 노선은 불안하게 공존했고 내부 폭로가 가장 큰 위험이 됐습니다.', effect: { gameDelta: { intelNetwork: 8, manpower: 80, stability: 3 }, careerTrust: -3, careerReputation: 5 } },
    ],
  },
  {
    id: 'historical-philippines-guerrilla-recognition',
    nationIds: ['philippines'], historicalYear: 1942, category: '필리핀 · 게릴라', title: 'USAFFE 계열과 후크발라합이 서로의 승인을 요구합니다',
    briefing: '지역 미군계 게릴라는 망명정부의 군 계통을, 후크발라합은 농민 기반의 독자 지휘와 토지·치안 개혁을 주장합니다.',
    stakes: '일본군에 맞선 공동전선과 전후 필리핀의 정치·토지 질서가 동시에 걸려 있습니다.',
    historicalBasis: '1942년 중부 루손에서 후크발라합이 결성되었고 여러 USAFFE 계열 게릴라와 협력·경쟁 관계를 형성했습니다.',
    sourceLabel: '미 육군 군사사센터 · Hukbalahap', sourceUrl: 'https://history.army.mil/Portals/143/Images/Publications/Publication%20By%20Title%20Images/H%20Pdf/CMH_Pub_93-8-1.pdf?ver=WX-sSv5zV5bt8iHYkNCZdg%3D%3D',
    choices: [
      { id: 'philippines-guerrilla-recognize', title: '모든 항일부대를 공식 인정한다', description: '정치 성향과 무관하게 무전·무기·정보 지원 대상에 포함합니다.', result: '공동전선은 넓어졌지만 망명정부 보수파가 전후 무장세력을 우려했습니다.', effect: { gameDelta: { intelNetwork: 10, manpower: 140, stability: -4 }, careerReputation: 8 } },
      { id: 'philippines-guerrilla-usaaffe', title: 'USAFFE 계통만 지원한다', description: '전전 군 계급과 망명정부 충성 선서를 인정 기준으로 삼습니다.', result: '지휘계통은 선명해졌지만 일부 농민 게릴라가 독자 노선으로 이탈했습니다.', effect: { divisionOrganization: 9, careerTrust: 7, gameDelta: { enemyPressure: 5, commandPoints: 6 } } },
      { id: 'philippines-guerrilla-council', title: '지역 공동작전평의회를 만든다', description: '각 조직은 정치 독립을 유지하고 일본군 정보·보급 목표만 공유합니다.', result: '완전한 통합은 아니지만 상호 오인전투가 줄고 지역별 작전분담이 시작됐습니다.', effect: { gameDelta: { intelNetwork: 7, stability: 6, commandPoints: 5 }, relationChange: 5 } },
    ],
  },
];
