import type { NationId } from './types';

export type HistoricalFlagKind = 'national' | 'state' | 'government-in-exile' | 'independence-movement' | 'wartime';
export type HistoricalFlagRatio = 'ratio-2-1' | 'ratio-19-10' | 'ratio-5-3' | 'ratio-10-7' | 'ratio-3-2';

export interface HistoricalFlagRecord {
  nationId: NationId;
  name: string;
  shortLabel: string;
  kind: HistoricalFlagKind;
  kindLabel: string;
  period: string;
  validFrom: number;
  validTo: number;
  ratio: HistoricalFlagRatio;
  historicalNote: string;
  sourceLabel: string;
  sourceUrl: string;
  containsSensitiveSymbol?: boolean;
}

export const historicalFlags: Record<NationId, HistoricalFlagRecord> = {
  britain: {
    nationId: 'britain',
    name: '영국 연합기(Union Flag)',
    shortLabel: '연합기',
    kind: 'national',
    kindLabel: '당시 국기',
    period: '1801년형 · 1942년 사용',
    validFrom: 1801,
    validTo: 1945,
    ratio: 'ratio-2-1',
    historicalNote: '잉글랜드·스코틀랜드·아일랜드의 십자 문양을 결합한 1801년형을 재현했습니다.',
    sourceLabel: '영국 국기협회',
    sourceUrl: 'https://www.flaginstitute.org/wp/uk-flags/the-union-jack-or-the-union-flag/',
  },
  usa: {
    nationId: 'usa',
    name: '미국 48성 성조기',
    shortLabel: '48성기',
    kind: 'national',
    kindLabel: '당시 국기',
    period: '1912–1959',
    validFrom: 1912,
    validTo: 1959,
    ratio: 'ratio-19-10',
    historicalNote: '1942년의 48개 주를 나타내도록 별을 6행×8열로 배열했습니다.',
    sourceLabel: '스미스소니언',
    sourceUrl: 'https://www.si.edu/spotlight/flag-day/flag-facts',
  },
  ussr: {
    nationId: 'ussr',
    name: '소비에트 연방 국기',
    shortLabel: '1936년형',
    kind: 'state',
    kindLabel: '당시 국기',
    period: '1936–1955',
    validFrom: 1936,
    validTo: 1955,
    ratio: 'ratio-2-1',
    historicalNote: '전후인 1955년에 정비된 도안이 아니라 제2차 세계대전 중 사용된 낫·망치·별 도안을 사용합니다.',
    sourceLabel: '1936년 소련 헌법기 도안 기록',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Flag_of_the_Soviet_Union_(1924%E2%80%931955,_3-2).svg',
  },
  germany: {
    nationId: 'germany',
    name: '독일국 국기',
    shortLabel: '1935년형',
    kind: 'state',
    kindLabel: '당시 정권기',
    period: '1935–1945',
    validFrom: 1935,
    validTo: 1945,
    ratio: 'ratio-5-3',
    historicalNote: '역사적 고증을 위해 당시 국가사회주의 정권이 사용한 국기를 표시합니다. 이는 이념을 미화하는 장식이 아닙니다.',
    sourceLabel: '독일 역사박물관 르모',
    sourceUrl: 'https://www.dhm.de/lemo/kapitel/ns-regime/innenpolitik/das-hakenkreuz',
    containsSensitiveSymbol: true,
  },
  japan: {
    nationId: 'japan',
    name: '일장기(1870년 포고 규격)',
    shortLabel: '일장기',
    kind: 'national',
    kindLabel: '당시 국기',
    period: '1870년 규격 · 1942년 사용',
    validFrom: 1870,
    validTo: 1945,
    ratio: 'ratio-10-7',
    historicalNote: '현행 규격이 아니라 세로 7:가로 10, 원이 깃대 쪽으로 1/100 치우친 당시 규격을 반영했습니다.',
    sourceLabel: '일본 국립국회도서관 국기 비례 연구',
    sourceUrl: 'https://ndlsearch.ndl.go.jp/books/R000000025-I009990002884779',
  },
  china: {
    nationId: 'china',
    name: '중화민국 청천백일만지홍기',
    shortLabel: '청천백일기',
    kind: 'national',
    kindLabel: '당시 국기',
    period: '1928년 제정 · 1942년 사용',
    validFrom: 1928,
    validTo: 1949,
    ratio: 'ratio-3-2',
    historicalNote: '국민정부가 1928년 전국에 공포한 붉은 바탕·청천백일 문양과 12개 광선을 재현했습니다.',
    sourceLabel: '중화민국 총통부',
    sourceUrl: 'https://www.president.gov.tw/Page/96',
  },
  india: {
    nationId: 'india',
    name: '인도 국민회의 스와라지기',
    shortLabel: '스와라지기',
    kind: 'independence-movement',
    kindLabel: '독립운동기',
    period: '1931–1947',
    validFrom: 1931,
    validTo: 1947,
    ratio: 'ratio-3-2',
    historicalNote: '1942년 인도는 독립국이 아니므로 현대 국기 대신 국민회의가 채택한 차르카 삼색기를 사용합니다.',
    sourceLabel: '인도 국기재단',
    sourceUrl: 'https://flagfoundationofindia.in/faq',
  },
  freefrance: {
    nationId: 'freefrance',
    name: '자유 프랑스 로렌 십자기',
    shortLabel: '자유 프랑스기',
    kind: 'government-in-exile',
    kindLabel: '망명정부·자유군기',
    period: '1940–1944',
    validFrom: 1940,
    validTo: 1944,
    ratio: 'ratio-3-2',
    historicalNote: '프랑스 삼색기 중앙에 자유 프랑스의 상징인 붉은 로렌 십자를 배치했습니다.',
    sourceLabel: '파리 해방박물관',
    sourceUrl: 'https://www.parismuseescollections.paris.fr/fr/musee-jean-moulin/oeuvres/drapeau-tricolore-francais-a-croix-de-lorraine',
  },
  italy: {
    nationId: 'italy',
    name: '이탈리아 왕국 국기',
    shortLabel: '왕국기',
    kind: 'national',
    kindLabel: '당시 국기',
    period: '1861–1946',
    validFrom: 1861,
    validTo: 1946,
    ratio: 'ratio-3-2',
    historicalNote: '현대 공화국 삼색기가 아니라 중앙에 사보이 왕가 방패를 둔 왕국 국기를 사용합니다.',
    sourceLabel: '이탈리아 대통령실',
    sourceUrl: 'https://www.quirinale.it/it/pagine/italian-tricolour-flag',
  },
  korea: {
    nationId: 'korea',
    name: '대한민국 임시정부 계열 태극기',
    shortLabel: '임시정부 태극기',
    kind: 'government-in-exile',
    kindLabel: '임시정부·광복군기',
    period: '1941년 사료 기반 · 1942년 사용 맥락',
    validFrom: 1941,
    validTo: 1945,
    ratio: 'ratio-3-2',
    historicalNote: '김구 서명문 태극기와 한국광복군 태극기 사료를 바탕으로 태극·4괘를 재현한 게임용 정돈 도안입니다.',
    sourceLabel: '독립기념관',
    sourceUrl: 'https://i815.or.kr/images/img_cooperation/2024/network/Leaflet_pdf_info_04.pdf',
  },
  vietnam: {
    nationId: 'vietnam',
    name: '베트민 금성홍기',
    shortLabel: '베트민기',
    kind: 'independence-movement',
    kindLabel: '독립운동기',
    period: '1941–1945 초기형',
    validFrom: 1941,
    validTo: 1945,
    ratio: 'ratio-3-2',
    historicalNote: '1945년 국가 제정 이후의 표현이 아니라 1941년 베트민 창립 당시 사용된 붉은 바탕과 노란 별을 표시합니다.',
    sourceLabel: '베트남 국립역사박물관',
    sourceUrl: 'https://vnmh.com.vn/en/Articles/3173/19229/exhibition-viet-minh-front-movement-for-national-liberation-1941-1951-goes-on-display-at-the-vietnam-national-museum-of-history.html',
  },
  indonesia: {
    nationId: 'indonesia',
    name: '인도네시아 민족운동 홍백기',
    shortLabel: '홍백기',
    kind: 'independence-movement',
    kindLabel: '독립운동기',
    period: '1928년 민족운동 사용 · 1945년 국기화',
    validFrom: 1928,
    validTo: 1945,
    ratio: 'ratio-3-2',
    historicalNote: '1942년에는 독립국 국기가 아니었으므로 인도네시아 민족주의 운동의 홍백기로 명시해 표시합니다.',
    sourceLabel: '인도네시아 국민협의회 역사 연구',
    sourceUrl: 'https://mpr.go.id/img/jurnal/file/160822_KjA%20dgn%20UNSOED%20%282022%29.pdf',
  },
  philippines: {
    nationId: 'philippines',
    name: '필리핀 영연방 전시 국기',
    shortLabel: '영연방 전시기',
    kind: 'wartime',
    kindLabel: '전시 국기',
    period: '1936년 규격 · 1941–1945 전시 배치',
    validFrom: 1936,
    validTo: 1946,
    ratio: 'ratio-2-1',
    historicalNote: '전쟁 상태를 나타내기 위해 붉은 띠를 위에 둔 영연방기 배치를 사용합니다.',
    sourceLabel: '필리핀 대통령 행정명령 제386호',
    sourceUrl: 'https://elibrary.judiciary.gov.ph/thebookshelf/showdocs/5/84473',
  },
};

export function getHistoricalFlag(nationId: NationId): HistoricalFlagRecord {
  return historicalFlags[nationId];
}
