import type { StrategicSiteType, Territory, TheaterId } from './types';

export interface StrategicFrontDefinition {
  id: string;
  name: string;
  theater: TheaterId;
  commandArea: string;
  historicalWindow: string;
  sourceUrl: string;
}

const EUROPE_SOURCE = 'https://history.army.mil/Research/Reference-Topics/Army-Campaigns/Brief-Summaries/World-War-II/World-War-II-European-African-Middle-Eastern-Theater/';
const ASIA_SOURCE = 'https://history.army.mil/Research/Reference-Topics/Army-Campaigns/Brief-Summaries/World-War-II/World-War-II-Asiatic-Pacific-Theater/';

export const strategicFronts: StrategicFrontDefinition[] = [
  { id: 'british-isles', name: '영국 본토 방공전선', theater: 'europe', commandArea: '런던·리버풀·스코틀랜드', historicalWindow: '1939–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'atlantic-lifeline', name: '대서양 생명선', theater: 'europe', commandArea: '아이슬란드–리버풀–서부접근로', historicalWindow: '1939–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'channel-coast', name: '해협·대서양 방벽', theater: 'europe', commandArea: '칼레–노르망디–브르타뉴', historicalWindow: '1940–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'occupied-france', name: '프랑스 점령·레지스탕스 전선', theater: 'europe', commandArea: '파리–리옹–마르세유', historicalWindow: '1940–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'low-countries', name: '저지대·스헬데 전선', theater: 'europe', commandArea: '로테르담–안트베르펜–브뤼셀', historicalWindow: '1940–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'reich-defense', name: '독일 본토 방어전선', theater: 'europe', commandArea: '함부르크–루르–베를린–뮌헨', historicalWindow: '1942–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'scandinavia', name: '노르웨이·북극항로 전선', theater: 'europe', commandArea: '나르비크–노르웨이–덴마크', historicalWindow: '1940–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'leningrad-karelia', name: '레닌그라드·카렐리야 전선', theater: 'europe', commandArea: '핀란드–카렐리야–레닌그라드', historicalWindow: '1941–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'baltic-belarus', name: '발트·벨라루스 전선', theater: 'europe', commandArea: '리가–민스크–스몰렌스크', historicalWindow: '1941–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'moscow-axis', name: '모스크바 방면군', theater: 'europe', commandArea: '스몰렌스크–모스크바', historicalWindow: '1941–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'ukraine-dnieper', name: '우크라이나·드네프르 전선', theater: 'europe', commandArea: '키이우–하르키우–크림', historicalWindow: '1941–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'stalingrad-don', name: '돈·스탈린그라드 전선', theater: 'europe', commandArea: '로스토프–스탈린그라드', historicalWindow: '1942–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'caucasus-oil', name: '캅카스·유전 전선', theater: 'europe', commandArea: '캅카스 산맥–바쿠', historicalWindow: '1942–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'central-europe', name: '중부유럽 방면', theater: 'europe', commandArea: '프라하–빈–부다페스트', historicalWindow: '1944–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'balkan-partisan', name: '발칸·유격전 전선', theater: 'europe', commandArea: '베오그라드–소피아–그리스', historicalWindow: '1941–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'italian-peninsula', name: '이탈리아 반도 전선', theater: 'europe', commandArea: '살레르노–카시노–안치오–포강', historicalWindow: '1943–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'western-mediterranean', name: '서부 지중해 상륙전선', theater: 'europe', commandArea: '카사블랑카–오랑–알제', historicalWindow: '1942–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'tunisia-front', name: '튀니지 전선', theater: 'europe', commandArea: '카세린–튀니스–비제르테', historicalWindow: '1942–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'western-desert', name: '서부사막 전선', theater: 'europe', commandArea: '트리폴리–엘아게일라–토브루크', historicalWindow: '1940–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'egypt-suez', name: '엘알라메인·수에즈 전선', theater: 'europe', commandArea: '엘알라메인–알렉산드리아–카이로–수에즈', historicalWindow: '1942–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'middle-east-corridor', name: '중동·페르시아 보급회랑', theater: 'europe', commandArea: '베이루트–바그다드–테헤란', historicalWindow: '1941–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'arctic-supply', name: '북극 수송·무르만스크 전선', theater: 'europe', commandArea: '스캐파플로–무르만스크–아르한겔스크', historicalWindow: '1941–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'cotentin-front', name: '코탕탱·셰르부르 전선', theater: 'europe', commandArea: '셰르부르–생로–캉', historicalWindow: '1944', sourceUrl: EUROPE_SOURCE },
  { id: 'rhineland-front', name: '라인란트·서부방벽 전선', theater: 'europe', commandArea: '아헨–쾰른–프랑크푸르트', historicalWindow: '1944–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'rzhev-vyazma', name: '르제프·뱌지마 돌출부', theater: 'europe', commandArea: '르제프–뱌지마–모스크바 서방', historicalWindow: '1941–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'kursk-orel', name: '쿠르스크·오룔 전선', theater: 'europe', commandArea: '오룔–쿠르스크–보로네시', historicalWindow: '1942–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'donbas-azov', name: '돈바스·아조프 전선', theater: 'europe', commandArea: '드네프로페트롭스크–스탈리노–마리우폴', historicalWindow: '1941–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'black-sea-coast', name: '흑해 북안 전선', theater: 'europe', commandArea: '오데사–니콜라예프–세바스토폴', historicalWindow: '1941–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'kuban-caucasus', name: '쿠반·캅카스 산악전선', theater: 'europe', commandArea: '마이코프–그로즈니–바쿠', historicalWindow: '1942–1943', sourceUrl: EUROPE_SOURCE },
  { id: 'adriatic-partisan', name: '아드리아해·유고슬라비아 전선', theater: 'europe', commandArea: '자그레브–사라예보–아드리아 해안', historicalWindow: '1941–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'sicily-calabria', name: '시칠리아·칼라브리아 전선', theater: 'europe', commandArea: '메시나–타란토–이탈리아 남단', historicalWindow: '1943', sourceUrl: EUROPE_SOURCE },
  { id: 'levant-iraq', name: '레반트·이라크 통신선', theater: 'europe', commandArea: '다마스쿠스–예루살렘–바스라', historicalWindow: '1941–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'india-base', name: '인도 병참·본토 방어구', theater: 'asia', commandArea: '델리–봄베이–캘커타–실론', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'imphal-kohima', name: '임팔·코히마 전선', theater: 'asia', commandArea: '레도–코히마–임팔', historicalWindow: '1944', sourceUrl: ASIA_SOURCE },
  { id: 'arakan-front', name: '아라칸 해안전선', theater: 'asia', commandArea: '치타공–아라칸–아키아브', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'north-burma', name: '북부 버마·레도 도로 전선', theater: 'asia', commandArea: '미치나–라시오–윈난', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'central-burma', name: '중부 버마 전선', theater: 'asia', commandArea: '친드윈–만달레이–랑군', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'malaya-singapore', name: '말라야·싱가포르 전선', theater: 'asia', commandArea: '쿠알라룸푸르–싱가포르', historicalWindow: '1941–1945', sourceUrl: ASIA_SOURCE },
  { id: 'north-china', name: '화북 전선', theater: 'asia', commandArea: '베이징–산둥–시안', historicalWindow: '1937–1945', sourceUrl: ASIA_SOURCE },
  { id: 'central-china', name: '화중·양쯔강 전선', theater: 'asia', commandArea: '상하이–난징–우한–창사', historicalWindow: '1937–1945', sourceUrl: ASIA_SOURCE },
  { id: 'south-china', name: '화남·대륙타통작전 전선', theater: 'asia', commandArea: '헝양–구이린–광저우', historicalWindow: '1938–1945', sourceUrl: ASIA_SOURCE },
  { id: 'chongqing-yunnan', name: '충칭·윈난 후방전선', theater: 'asia', commandArea: '충칭–쿤밍–버마로드', historicalWindow: '1938–1945', sourceUrl: ASIA_SOURCE },
  { id: 'indochina-front', name: '인도차이나 전선', theater: 'asia', commandArea: '하노이–사이공–중국 국경', historicalWindow: '1940–1945', sourceUrl: ASIA_SOURCE },
  { id: 'manchuria-korea', name: '만주·한반도 전략구', theater: 'asia', commandArea: '하얼빈–묵덴–서울–부산', historicalWindow: '1931–1945', sourceUrl: ASIA_SOURCE },
  { id: 'japan-home', name: '일본 본토 방공전선', theater: 'asia', commandArea: '도쿄–오사카·구레–홋카이도', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'philippines', name: '필리핀 군도 전선', theater: 'asia', commandArea: '바탄–마닐라–레이테–민다나오', historicalWindow: '1941–1945', sourceUrl: ASIA_SOURCE },
  { id: 'east-indies', name: '네덜란드령 동인도 전선', theater: 'asia', commandArea: '수마트라–자바–보르네오–티모르', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'papua', name: '파푸아·코코다 전선', theater: 'asia', commandArea: '부나–코코다–포트모르즈비', historicalWindow: '1942–1943', sourceUrl: ASIA_SOURCE },
  { id: 'new-guinea', name: '뉴기니 북안 전선', theater: 'asia', commandArea: '라에–홀란디아–비악', historicalWindow: '1943–1944', sourceUrl: ASIA_SOURCE },
  { id: 'solomons', name: '솔로몬·라바울 전선', theater: 'asia', commandArea: '과달카날–부건빌–라바울', historicalWindow: '1942–1944', sourceUrl: ASIA_SOURCE },
  { id: 'central-pacific', name: '중부태평양 도서 전선', theater: 'asia', commandArea: '마셜–트루크–사이판–괌–팔라우', historicalWindow: '1943–1945', sourceUrl: ASIA_SOURCE },
  { id: 'north-pacific', name: '북태평양·알류샨 전선', theater: 'asia', commandArea: '홋카이도–애투–알류샨', historicalWindow: '1942–1943', sourceUrl: ASIA_SOURCE },
  { id: 'southwest-pacific', name: '남서태평양 병참전선', theater: 'asia', commandArea: '다윈–브리즈번–산호해', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'bengal-assam', name: '벵골·아삼 접근로', theater: 'asia', commandArea: '치타공–디마푸르–임팔', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'irrawaddy-front', name: '이라와디·메이크틸라 전선', theater: 'asia', commandArea: '메이크틸라–페구–랑군', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'thailand-malaya', name: '태국·말라야 종단전선', theater: 'asia', commandArea: '방콕–페낭–쿠알라룸푸르', historicalWindow: '1941–1945', sourceUrl: ASIA_SOURCE },
  { id: 'yellow-river', name: '황허·중원 전선', theater: 'asia', commandArea: '타이위안–정저우–톈진', historicalWindow: '1937–1945', sourceUrl: ASIA_SOURCE },
  { id: 'wuhan-nanchang', name: '우한·난창 방면', theater: 'asia', commandArea: '난창–창더–우한', historicalWindow: '1938–1945', sourceUrl: ASIA_SOURCE },
  { id: 'south-manchuria-korea', name: '남만주·조선 철도전략구', theater: 'asia', commandArea: '신징–다이렌–신의주–평양', historicalWindow: '1931–1945', sourceUrl: ASIA_SOURCE },
  { id: 'home-islands-industry', name: '일본 본토 산업·해군기지망', theater: 'asia', commandArea: '요코스카–나고야–히로시마–사세보', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'luzon-front', name: '루손 중부·마닐라 전선', theater: 'asia', commandArea: '링가옌–클라크–마닐라–바탄', historicalWindow: '1941–1945', sourceUrl: ASIA_SOURCE },
  { id: 'visayas-mindanao', name: '비사야·민다나오 전선', theater: 'asia', commandArea: '세부–레이테–다바오', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'bismarck-archipelago', name: '비스마르크 제도 전선', theater: 'asia', commandArea: '애드미럴티–캐비엥–라바울', historicalWindow: '1943–1944', sourceUrl: ASIA_SOURCE },
  { id: 'eastern-mandates', name: '동부 위임통치령 전선', theater: 'asia', commandArea: '콰잘레인–에니웨톡–마셜 제도', historicalWindow: '1943–1944', sourceUrl: ASIA_SOURCE },
  { id: 'gilbert-islands', name: '길버트 제도 상륙전선', theater: 'asia', commandArea: '마킨–타라와–마셜 접근로', historicalWindow: '1943', sourceUrl: ASIA_SOURCE },
  { id: 'aleutian-chain', name: '알류샨 열도 전선', theater: 'asia', commandArea: '더치하버–키스카–애투', historicalWindow: '1942–1943', sourceUrl: ASIA_SOURCE },
  { id: 'normandy-bocage', name: '노르망디·보카주 전선', theater: 'europe', commandArea: '캉–생로–셰르부르–브레스트', historicalWindow: '1944', sourceUrl: EUROPE_SOURCE },
  { id: 'rhone-provence', name: '프로방스·론 계곡 전선', theater: 'europe', commandArea: '툴롱–마르세유–리옹', historicalWindow: '1944–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'norway-narvik', name: '노르웨이·나르비크 전선', theater: 'europe', commandArea: '오슬로–나르비크–트롬쇠', historicalWindow: '1940–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'minsk-berezina', name: '민스크·베레지나 전선', theater: 'europe', commandArea: '민스크–보리소프–베레지나 강', historicalWindow: '1941–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'crimea-sevastopol', name: '크림·세바스토폴 전선', theater: 'europe', commandArea: '페레코프–세바스토폴–케르치', historicalWindow: '1941–1944', sourceUrl: EUROPE_SOURCE },
  { id: 'aegean-greece', name: '그리스·에게해 전선', theater: 'europe', commandArea: '아테네–크레타–에게해 제도', historicalWindow: '1941–1945', sourceUrl: EUROPE_SOURCE },
  { id: 'chindwin-burma', name: '친드윈·만달레이 전선', theater: 'asia', commandArea: '친드윈 강–만달레이–메이크틸라', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
  { id: 'singapore-johor', name: '조호르·싱가포르 전선', theater: 'asia', commandArea: '조호르바루–싱가포르 해협–셀레타', historicalWindow: '1941–1945', sourceUrl: ASIA_SOURCE },
  { id: 'lower-yangtze', name: '상하이·난징 하양쯔 전선', theater: 'asia', commandArea: '상하이–난징–항저우', historicalWindow: '1937–1945', sourceUrl: ASIA_SOURCE },
  { id: 'korea-liberation', name: '조선 국내진공·해방 전선', theater: 'asia', commandArea: '경성–평양–부산–압록강', historicalWindow: '1940–1945', sourceUrl: ASIA_SOURCE },
  { id: 'ryukyu-okinawa', name: '류큐·오키나와 전선', theater: 'asia', commandArea: '오키나와–게라마–류큐 항로', historicalWindow: '1944–1945', sourceUrl: ASIA_SOURCE },
  { id: 'philippine-resistance', name: '필리핀 군도 저항전선', theater: 'asia', commandArea: '루손–레이테–민다나오 게릴라 지구', historicalWindow: '1942–1945', sourceUrl: ASIA_SOURCE },
];

const baseEnhancements: Record<string, Partial<Territory>> = {
  britain: { name: '런던·남부 잉글랜드', frontId: 'british-isles', siteType: 'capital', labelTier: 1, historicalNote: '전시내각, 철도와 남부 방공망의 중심' },
  atlantic: { name: '서부접근로', frontId: 'atlantic-lifeline', siteType: 'sea', labelTier: 1 },
  channel: { name: '도버·영불해협', frontId: 'channel-coast', siteType: 'sea', labelTier: 1 },
  france: { name: '파리·중부 프랑스', frontId: 'occupied-france', siteType: 'capital', labelTier: 1 },
  lowlands: { name: '브뤼셀·벨기에', frontId: 'low-countries', siteType: 'city', labelTier: 2 },
  germany: { name: '베를린', frontId: 'reich-defense', siteType: 'capital', labelTier: 1 },
  denmark: { name: '코펜하겐·덴마크 해협', frontId: 'scandinavia', siteType: 'port', labelTier: 2 },
  norway: { name: '오슬로·노르웨이', frontId: 'norway-narvik', siteType: 'capital', labelTier: 2 },
  finland: { name: '핀란드·카렐리야', frontId: 'leningrad-karelia', siteType: 'front', labelTier: 2 },
  poland: { name: '바르샤바·폴란드 총독부', frontId: 'baltic-belarus', siteType: 'capital', labelTier: 1 },
  baltic: { name: '리가·발트 전선', frontId: 'baltic-belarus', siteType: 'front', labelTier: 2 },
  moscow: { name: '모스크바', frontId: 'moscow-axis', siteType: 'capital', labelTier: 1 },
  ukraine: { name: '키예프·드네프르', frontId: 'ukraine-dnieper', siteType: 'city', labelTier: 1, historicalNote: '1942년 지도·문헌에 널리 쓰인 당시 영문명 Kiev를 기준으로 표기' },
  caucasus: { name: '캅카스 산악전선', frontId: 'caucasus-oil', siteType: 'front', labelTier: 2 },
  alps: { name: '알프스·북이탈리아 접근로', frontId: 'italian-peninsula', siteType: 'front', labelTier: 3 },
  italy: { name: '로마', frontId: 'italian-peninsula', siteType: 'capital', labelTier: 1 },
  balkans: { name: '발칸 내륙', frontId: 'balkan-partisan', siteType: 'region', labelTier: 2 },
  anatolia: { name: '앙카라·아나톨리아', frontId: 'middle-east-corridor', siteType: 'capital', labelTier: 2 },
  spain: { name: '마드리드·이베리아', frontId: 'western-mediterranean', siteType: 'capital', labelTier: 2 },
  morocco: { name: '모로코 내륙', frontId: 'western-mediterranean', siteType: 'region', labelTier: 3 },
  algeria: { name: '알제리 내륙', frontId: 'western-mediterranean', siteType: 'region', labelTier: 3 },
  tunisia: { name: '비제르테·북튀니지', frontId: 'tunisia-front', siteType: 'port', labelTier: 2 },
  sicily: { name: '팔레르모·시칠리아', frontId: 'italian-peninsula', siteType: 'island', labelTier: 2 },
  malta: { name: '발레타·몰타', frontId: 'italian-peninsula', siteType: 'fortress', labelTier: 1 },
  libya: { name: '리비아 사막 회랑', frontId: 'western-desert', siteType: 'front', labelTier: 3 },
  egypt: { name: '카이로 지휘구', frontId: 'egypt-suez', siteType: 'capital', labelTier: 1 },
  levant: { name: '다마스쿠스·레반트', frontId: 'middle-east-corridor', siteType: 'city', labelTier: 2 },
  india: { name: '델리·인도 총독부', frontId: 'india-base', siteType: 'capital', labelTier: 1 },
  ceylon: { name: '콜롬보·실론', frontId: 'india-base', siteType: 'port', labelTier: 2 },
  assam: { name: '레도·아삼 보급기지', frontId: 'imphal-kohima', siteType: 'front', labelTier: 2 },
  burma: { name: '랑군·남부 버마', frontId: 'central-burma', siteType: 'capital', labelTier: 1 },
  malaya: { name: '쿠알라룸푸르·말라야', frontId: 'malaya-singapore', siteType: 'city', labelTier: 2 },
  singapore: { name: '싱가포르', frontId: 'singapore-johor', siteType: 'fortress', labelTier: 1 },
  mongolia: { name: '울란바토르·몽골', frontId: 'manchuria-korea', siteType: 'capital', labelTier: 2 },
  china_interior: { name: '충칭', frontId: 'chongqing-yunnan', siteType: 'capital', labelTier: 1 },
  yunnan: { name: '쿤밍·윈난', frontId: 'chongqing-yunnan', siteType: 'city', labelTier: 1 },
  north_china: { name: '베이징(북평)·화북', frontId: 'north-china', siteType: 'city', labelTier: 1, historicalNote: '점령정부의 베이징 명칭과 중화민국의 북평 명칭을 함께 표기' },
  central_china: { name: '우한·양쯔강', frontId: 'central-china', siteType: 'city', labelTier: 1 },
  south_china: { name: '광저우·화남', frontId: 'south-china', siteType: 'port', labelTier: 1 },
  indochina: { name: '하노이·북부 인도차이나', frontId: 'indochina-front', siteType: 'city', labelTier: 1 },
  soviet_far_east: { name: '블라디보스토크·연해주', frontId: 'manchuria-korea', siteType: 'port', labelTier: 1 },
  manchuria: { name: '묵덴(봉천)·남만주', frontId: 'manchuria-korea', siteType: 'city', labelTier: 1 },
  korea: { name: '경성·조선 중부', frontId: 'korea-liberation', siteType: 'capital', labelTier: 1, historicalNote: '일제강점기 행정명 경성을 1942년 표기로 사용' },
  japan_home: { name: '도쿄·간토', frontId: 'japan-home', siteType: 'capital', labelTier: 1 },
  philippines: { name: '마닐라·루손', frontId: 'philippines', siteType: 'capital', labelTier: 1 },
  dutch_east_indies: { name: '바타비아·자바', frontId: 'east-indies', siteType: 'capital', labelTier: 1 },
  new_guinea: { name: '부나·고나 교두보', frontId: 'papua', siteType: 'front', labelTier: 1 },
  coral_sea: { name: '산호해 항로', frontId: 'southwest-pacific', siteType: 'sea', labelTier: 2 },
  solomons: { name: '과달카날', frontId: 'solomons', siteType: 'island', labelTier: 1 },
  midway: { name: '미드웨이 환초', frontId: 'central-pacific', siteType: 'island', labelTier: 1 },
  hawaii: { name: '진주만·하와이', frontId: 'central-pacific', siteType: 'port', labelTier: 1 },
};

type SiteDraft = Omit<Territory, 'x' | 'y'> & { px: number; py: number; siteType: StrategicSiteType; theater: TheaterId };
const expandedPoints: Record<TheaterId, Record<string, { x: number; y: number }>> = { europe: {}, asia: {} };

function site({ px, py, ...draft }: SiteDraft): Territory {
  expandedPoints[draft.theater][draft.id] = { x: px, y: py };
  return { ...draft, x: px / 12, y: py / 7.6 };
}

const expandedTerritories: Territory[] = [
  // Europe, the Mediterranean and the Middle East
  site({ id: 'scotland', name: '스코틀랜드·스캐파플로', region: '영국 본토', px: 302, py: 285, controller: 'allies', ownerId: 'britain', value: 7, supply: 86, terrain: '해군기지', neighbors: ['britain', 'liverpool', 'narvik'], theater: 'europe', siteType: 'port', frontId: 'british-isles', labelTier: 2 }),
  site({ id: 'liverpool', name: '리버풀·대서양 항구', region: '영국 본토', px: 301, py: 344, controller: 'allies', ownerId: 'britain', value: 9, supply: 94, terrain: '항구 도시', neighbors: ['britain', 'atlantic', 'belfast', 'scotland'], theater: 'europe', siteType: 'port', frontId: 'atlantic-lifeline', labelTier: 1 }),
  site({ id: 'belfast', name: '벨파스트·북아일랜드', region: '영국 본토', px: 274, py: 339, controller: 'allies', ownerId: 'britain', value: 5, supply: 81, terrain: '항구 도시', neighbors: ['liverpool', 'atlantic'], theater: 'europe', siteType: 'port', frontId: 'atlantic-lifeline', labelTier: 3 }),
  site({ id: 'iceland', name: '레이캬비크·아이슬란드', region: '북대서양', px: 185, py: 210, controller: 'allies', ownerId: 'britain', value: 6, supply: 72, terrain: '해군기지', neighbors: ['atlantic', 'scotland', 'narvik'], theater: 'europe', siteType: 'port', frontId: 'atlantic-lifeline', labelTier: 2 }),
  site({ id: 'netherlands', name: '로테르담·네덜란드', region: '저지대', px: 454, py: 380, controller: 'axis', ownerId: 'germany', value: 8, supply: 92, terrain: '항구 도시', neighbors: ['lowlands', 'ruhr', 'hamburg'], theater: 'europe', siteType: 'port', frontId: 'low-countries', labelTier: 1 }),
  site({ id: 'calais', name: '칼레·파드칼레', region: '해협 전선', px: 385, py: 423, controller: 'axis', ownerId: 'germany', value: 7, supply: 88, terrain: '요새 해안', neighbors: ['channel', 'lowlands', 'normandy', 'france'], theater: 'europe', siteType: 'fortress', frontId: 'channel-coast', labelTier: 2 }),
  site({ id: 'normandy', name: '노르망디·캉', region: '서부 전선', px: 371, py: 466, controller: 'axis', ownerId: 'germany', value: 9, supply: 78, terrain: '해안 구릉', neighbors: ['channel', 'calais', 'france', 'brittany'], theater: 'europe', siteType: 'front', frontId: 'normandy-bocage', labelTier: 1, historicalNote: '노르망디 상륙과 셰르부르·캉 전투 축' }),
  site({ id: 'brittany', name: '브레스트·브르타뉴', region: '서부 전선', px: 326, py: 481, controller: 'axis', ownerId: 'germany', value: 7, supply: 73, terrain: '항구 해안', neighbors: ['normandy', 'france', 'atlantic'], theater: 'europe', siteType: 'port', frontId: 'normandy-bocage', labelTier: 2 }),
  site({ id: 'lyon', name: '리옹·론 회랑', region: '점령 프랑스', px: 445, py: 516, controller: 'axis', ownerId: 'germany', value: 7, supply: 81, terrain: '도시', neighbors: ['france', 'marseille', 'alps'], theater: 'europe', siteType: 'city', frontId: 'rhone-provence', labelTier: 2 }),
  site({ id: 'marseille', name: '마르세유·툴롱', region: '남부 프랑스', px: 438, py: 557, controller: 'axis', ownerId: 'germany', value: 8, supply: 78, terrain: '항구 도시', neighbors: ['lyon', 'alps', 'spain', 'algeria'], theater: 'europe', siteType: 'port', frontId: 'rhone-provence', labelTier: 1 }),
  site({ id: 'ruhr', name: '루르 공업지대', region: '독일 본토', px: 484, py: 410, controller: 'axis', ownerId: 'germany', value: 12, supply: 98, terrain: '공업 도시', neighbors: ['lowlands', 'netherlands', 'germany', 'hamburg'], theater: 'europe', siteType: 'city', frontId: 'reich-defense', labelTier: 1 }),
  site({ id: 'hamburg', name: '함부르크·북해 항구', region: '독일 본토', px: 508, py: 357, controller: 'axis', ownerId: 'germany', value: 9, supply: 96, terrain: '항구 도시', neighbors: ['denmark', 'netherlands', 'ruhr', 'germany'], theater: 'europe', siteType: 'port', frontId: 'reich-defense', labelTier: 2 }),
  site({ id: 'munich', name: '뮌헨·바이에른', region: '독일 본토', px: 532, py: 477, controller: 'axis', ownerId: 'germany', value: 8, supply: 91, terrain: '도시', neighbors: ['germany', 'alps', 'prague', 'vienna'], theater: 'europe', siteType: 'city', frontId: 'reich-defense', labelTier: 2 }),
  site({ id: 'east_prussia', name: '쾨니히스베르크·동프로이센', region: '발트 전선', px: 625, py: 343, controller: 'axis', ownerId: 'germany', value: 8, supply: 85, terrain: '요새 해안', neighbors: ['poland', 'baltic', 'germany'], theater: 'europe', siteType: 'fortress', frontId: 'baltic-belarus', labelTier: 2 }),
  site({ id: 'narvik', name: '나르비크·철광석 항로', region: '북극권', px: 512, py: 168, controller: 'axis', ownerId: 'germany', value: 7, supply: 55, terrain: '산악 항구', neighbors: ['norway', 'finland', 'scotland', 'iceland'], theater: 'europe', siteType: 'port', frontId: 'norway-narvik', labelTier: 1 }),
  site({ id: 'leningrad', name: '레닌그라드', region: '북부 동부전선', px: 731, py: 282, controller: 'allies', ownerId: 'ussr', value: 12, supply: 53, terrain: '요새 도시', neighbors: ['finland', 'baltic', 'smolensk'], theater: 'europe', siteType: 'fortress', frontId: 'leningrad-karelia', labelTier: 1 }),
  site({ id: 'minsk', name: '민스크', region: '벨라루스 전선', px: 690, py: 388, controller: 'axis', ownerId: 'germany', value: 8, supply: 67, terrain: '도시 평야', neighbors: ['poland', 'baltic', 'smolensk', 'ukraine'], theater: 'europe', siteType: 'city', frontId: 'minsk-berezina', labelTier: 2 }),
  site({ id: 'smolensk', name: '스몰렌스크', region: '모스크바 방면', px: 764, py: 383, controller: 'axis', ownerId: 'germany', value: 8, supply: 59, terrain: '도시 삼림', neighbors: ['minsk', 'leningrad', 'moscow', 'kharkov'], theater: 'europe', siteType: 'front', frontId: 'moscow-axis', labelTier: 1 }),
  site({ id: 'kharkov', name: '하르키우', region: '우크라이나 전선', px: 790, py: 471, controller: 'axis', ownerId: 'germany', value: 9, supply: 65, terrain: '공업 도시', neighbors: ['ukraine', 'smolensk', 'stalingrad', 'rostov', 'crimea'], theater: 'europe', siteType: 'city', frontId: 'ukraine-dnieper', labelTier: 1 }),
  site({ id: 'stalingrad', name: '스탈린그라드', region: '볼가 전선', px: 875, py: 487, controller: 'allies', ownerId: 'ussr', value: 12, supply: 52, terrain: '강변 도시', neighbors: ['kharkov', 'rostov', 'caucasus'], theater: 'europe', siteType: 'fortress', frontId: 'stalingrad-don', labelTier: 1 }),
  site({ id: 'rostov', name: '로스토프나도누', region: '돈 전선', px: 828, py: 535, controller: 'axis', ownerId: 'germany', value: 9, supply: 54, terrain: '강변 도시', neighbors: ['kharkov', 'stalingrad', 'crimea', 'caucasus'], theater: 'europe', siteType: 'city', frontId: 'stalingrad-don', labelTier: 1 }),
  site({ id: 'crimea', name: '세바스토폴·크림', region: '흑해 전선', px: 763, py: 552, controller: 'axis', ownerId: 'germany', value: 9, supply: 49, terrain: '요새 해안', neighbors: ['ukraine', 'kharkov', 'rostov', 'balkans'], theater: 'europe', siteType: 'fortress', frontId: 'crimea-sevastopol', labelTier: 1 }),
  site({ id: 'baku', name: '바쿠 유전', region: '캅카스', px: 917, py: 627, controller: 'allies', ownerId: 'ussr', value: 13, supply: 62, terrain: '산악 도시', neighbors: ['caucasus', 'stalingrad', 'tehran'], theater: 'europe', siteType: 'city', frontId: 'caucasus-oil', labelTier: 1 }),
  site({ id: 'prague', name: '프라하·보헤미아', region: '중부 유럽', px: 574, py: 456, controller: 'axis', ownerId: 'germany', value: 8, supply: 91, terrain: '공업 도시', neighbors: ['germany', 'munich', 'vienna', 'poland'], theater: 'europe', siteType: 'city', frontId: 'central-europe', labelTier: 2 }),
  site({ id: 'vienna', name: '빈', region: '중부 유럽', px: 598, py: 500, controller: 'axis', ownerId: 'germany', value: 9, supply: 91, terrain: '도시', neighbors: ['munich', 'prague', 'budapest', 'alps'], theater: 'europe', siteType: 'city', frontId: 'central-europe', labelTier: 1 }),
  site({ id: 'budapest', name: '부다페스트', region: '중부 유럽', px: 646, py: 505, controller: 'axis', value: 8, supply: 75, terrain: '강변 도시', neighbors: ['vienna', 'poland', 'balkans', 'bucharest'], theater: 'europe', siteType: 'city', frontId: 'central-europe', labelTier: 1 }),
  site({ id: 'bucharest', name: '부쿠레슈티·플로이에슈티', region: '발칸', px: 708, py: 538, controller: 'axis', value: 10, supply: 74, terrain: '도시 평야', neighbors: ['budapest', 'ukraine', 'crimea', 'sofia', 'balkans'], theater: 'europe', siteType: 'city', frontId: 'balkan-partisan', labelTier: 1 }),
  site({ id: 'belgrade', name: '베오그라드', region: '발칸', px: 625, py: 551, controller: 'axis', ownerId: 'germany', value: 7, supply: 58, terrain: '강변 도시', neighbors: ['balkans', 'budapest', 'sofia', 'greece'], theater: 'europe', siteType: 'city', frontId: 'balkan-partisan', labelTier: 2 }),
  site({ id: 'sofia', name: '소피아', region: '발칸', px: 679, py: 572, controller: 'axis', value: 6, supply: 63, terrain: '산악 도시', neighbors: ['belgrade', 'bucharest', 'greece', 'anatolia'], theater: 'europe', siteType: 'city', frontId: 'balkan-partisan', labelTier: 2 }),
  site({ id: 'greece', name: '아테네·그리스', region: '에게해', px: 650, py: 618, controller: 'axis', ownerId: 'germany', value: 7, supply: 57, terrain: '항구 구릉', neighbors: ['balkans', 'belgrade', 'sofia', 'crete', 'sicily'], theater: 'europe', siteType: 'port', frontId: 'aegean-greece', labelTier: 1 }),
  site({ id: 'crete', name: '크레타', region: '동부 지중해', px: 685, py: 659, controller: 'axis', ownerId: 'germany', value: 6, supply: 48, terrain: '도서 산악', neighbors: ['greece', 'egypt', 'levant'], theater: 'europe', siteType: 'island', frontId: 'aegean-greece', labelTier: 2 }),
  site({ id: 'naples', name: '나폴리', region: '이탈리아 전선', px: 571, py: 595, controller: 'axis', ownerId: 'italy', value: 8, supply: 80, terrain: '항구 도시', neighbors: ['italy', 'salerno', 'sicily'], theater: 'europe', siteType: 'port', frontId: 'italian-peninsula', labelTier: 1 }),
  site({ id: 'salerno', name: '살레르노', region: '이탈리아 전선', px: 581, py: 613, controller: 'axis', ownerId: 'italy', value: 6, supply: 65, terrain: '해안 구릉', neighbors: ['naples', 'monte_cassino', 'sicily'], theater: 'europe', siteType: 'front', frontId: 'italian-peninsula', labelTier: 2 }),
  site({ id: 'monte_cassino', name: '몬테카시노·구스타프선', region: '이탈리아 전선', px: 566, py: 574, controller: 'axis', ownerId: 'italy', value: 8, supply: 52, terrain: '산악 요새', neighbors: ['naples', 'salerno', 'anzio', 'italy'], theater: 'europe', siteType: 'fortress', frontId: 'italian-peninsula', labelTier: 1 }),
  site({ id: 'anzio', name: '안치오 교두보', region: '이탈리아 전선', px: 552, py: 563, controller: 'axis', ownerId: 'italy', value: 6, supply: 58, terrain: '해안', neighbors: ['italy', 'monte_cassino', 'po_valley'], theater: 'europe', siteType: 'front', frontId: 'italian-peninsula', labelTier: 2 }),
  site({ id: 'po_valley', name: '볼로냐·포강 계곡', region: '북이탈리아', px: 548, py: 526, controller: 'axis', ownerId: 'italy', value: 9, supply: 85, terrain: '평야 도시', neighbors: ['alps', 'italy', 'anzio', 'vienna'], theater: 'europe', siteType: 'front', frontId: 'italian-peninsula', labelTier: 1 }),
  site({ id: 'casablanca', name: '카사블랑카', region: '프랑스령 모로코', px: 278, py: 686, controller: 'axis', value: 8, supply: 70, terrain: '항구 도시', neighbors: ['morocco', 'atlantic', 'oran'], theater: 'europe', siteType: 'port', frontId: 'western-mediterranean', labelTier: 1 }),
  site({ id: 'oran', name: '오랑', region: '알제리', px: 372, py: 682, controller: 'axis', value: 7, supply: 68, terrain: '항구 도시', neighbors: ['casablanca', 'algeria', 'algiers'], theater: 'europe', siteType: 'port', frontId: 'western-mediterranean', labelTier: 1 }),
  site({ id: 'algiers', name: '알제', region: '알제리', px: 445, py: 671, controller: 'axis', value: 8, supply: 76, terrain: '항구 도시', neighbors: ['oran', 'algeria', 'kasserine', 'marseille'], theater: 'europe', siteType: 'port', frontId: 'western-mediterranean', labelTier: 1 }),
  site({ id: 'kasserine', name: '카세린 고개', region: '튀니지 전선', px: 508, py: 696, controller: 'axis', ownerId: 'italy', value: 6, supply: 42, terrain: '산악', neighbors: ['algiers', 'tunisia', 'tunis', 'el_agheila'], theater: 'europe', siteType: 'front', frontId: 'tunisia-front', labelTier: 1 }),
  site({ id: 'tunis', name: '튀니스', region: '튀니지 전선', px: 532, py: 661, controller: 'axis', ownerId: 'italy', value: 9, supply: 73, terrain: '항구 도시', neighbors: ['tunisia', 'kasserine', 'sicily', 'tripoli'], theater: 'europe', siteType: 'port', frontId: 'tunisia-front', labelTier: 1 }),
  site({ id: 'tripoli', name: '트리폴리', region: '리비아', px: 626, py: 701, controller: 'axis', ownerId: 'italy', value: 8, supply: 61, terrain: '항구 도시', neighbors: ['tunis', 'libya', 'el_agheila', 'malta'], theater: 'europe', siteType: 'port', frontId: 'western-desert', labelTier: 1 }),
  site({ id: 'el_agheila', name: '엘아게일라', region: '서부사막', px: 686, py: 707, controller: 'axis', ownerId: 'italy', value: 5, supply: 31, terrain: '사막', neighbors: ['tripoli', 'libya', 'tobruk', 'kasserine'], theater: 'europe', siteType: 'front', frontId: 'western-desert', labelTier: 2 }),
  site({ id: 'tobruk', name: '토브루크', region: '서부사막', px: 749, py: 697, controller: 'axis', ownerId: 'italy', value: 9, supply: 46, terrain: '요새 항구', neighbors: ['libya', 'el_agheila', 'el_alamein', 'egypt'], theater: 'europe', siteType: 'fortress', frontId: 'western-desert', labelTier: 1 }),
  site({ id: 'el_alamein', name: '엘알라메인', region: '이집트-리비아 전선', px: 792, py: 700, controller: 'allies', ownerId: 'britain', value: 10, supply: 62, terrain: '사막 요새', neighbors: ['tobruk', 'egypt', 'alexandria'], theater: 'europe', siteType: 'front', frontId: 'egypt-suez', labelTier: 1 }),
  site({ id: 'alexandria', name: '알렉산드리아', region: '이집트', px: 816, py: 689, controller: 'allies', ownerId: 'britain', value: 9, supply: 88, terrain: '해군기지', neighbors: ['el_alamein', 'egypt', 'suez', 'crete'], theater: 'europe', siteType: 'port', frontId: 'egypt-suez', labelTier: 1 }),
  site({ id: 'cairo', name: '카이로', region: '이집트', px: 835, py: 706, controller: 'allies', ownerId: 'britain', value: 11, supply: 91, terrain: '도시', neighbors: ['egypt', 'alexandria', 'suez', 'levant'], theater: 'europe', siteType: 'capital', frontId: 'egypt-suez', labelTier: 1 }),
  site({ id: 'suez', name: '수에즈 운하', region: '이집트', px: 858, py: 696, controller: 'allies', ownerId: 'britain', value: 13, supply: 94, terrain: '요새 항구', neighbors: ['cairo', 'alexandria', 'levant', 'baghdad'], theater: 'europe', siteType: 'port', frontId: 'egypt-suez', labelTier: 1 }),
  site({ id: 'beirut', name: '베이루트', region: '레반트', px: 862, py: 652, controller: 'allies', ownerId: 'freefrance', value: 7, supply: 76, terrain: '항구 도시', neighbors: ['levant', 'anatolia', 'suez', 'baghdad'], theater: 'europe', siteType: 'port', frontId: 'middle-east-corridor', labelTier: 2 }),
  site({ id: 'baghdad', name: '바그다드', region: '이라크 보급회랑', px: 941, py: 675, controller: 'allies', ownerId: 'britain', value: 8, supply: 73, terrain: '강변 도시', neighbors: ['beirut', 'suez', 'tehran'], theater: 'europe', siteType: 'city', frontId: 'middle-east-corridor', labelTier: 1 }),
  site({ id: 'tehran', name: '테헤란·페르시아 회랑', region: '이란', px: 1002, py: 631, controller: 'allies', ownerId: 'ussr', value: 9, supply: 78, terrain: '고원 도시', neighbors: ['baghdad', 'baku', 'caucasus'], theater: 'europe', siteType: 'city', frontId: 'middle-east-corridor', labelTier: 1 }),

  // Additional regional sectors use the same calibrated coordinates as the archive scan.
  site({ id: 'plymouth', name: '플리머스·웨스턴어프로치', region: '영국 본토', px: 306, py: 405, controller: 'allies', ownerId: 'britain', value: 8, supply: 88, terrain: '해군기지', neighbors: ['britain', 'liverpool', 'atlantic', 'portsmouth'], theater: 'europe', siteType: 'port', frontId: 'atlantic-lifeline', labelTier: 2 }),
  site({ id: 'portsmouth', name: '포츠머스·사우샘프턴', region: '영국 본토', px: 338, py: 399, controller: 'allies', ownerId: 'britain', value: 9, supply: 93, terrain: '해군기지', neighbors: ['britain', 'channel', 'plymouth', 'calais'], theater: 'europe', siteType: 'port', frontId: 'british-isles', labelTier: 2 }),
  site({ id: 'dunkirk', name: '됭케르크', region: '해협 전선', px: 400, py: 413, controller: 'axis', ownerId: 'germany', value: 7, supply: 77, terrain: '항구 도시', neighbors: ['calais', 'lowlands', 'antwerp'], theater: 'europe', siteType: 'port', frontId: 'channel-coast', labelTier: 2 }),
  site({ id: 'antwerp', name: '안트베르펜·스헬데', region: '저지대', px: 438, py: 401, controller: 'axis', ownerId: 'germany', value: 10, supply: 90, terrain: '항구 도시', neighbors: ['dunkirk', 'lowlands', 'netherlands', 'ruhr'], theater: 'europe', siteType: 'port', frontId: 'low-countries', labelTier: 1 }),
  site({ id: 'bordeaux', name: '보르도·비시 프랑스', region: '남서 프랑스', px: 376, py: 535, controller: 'axis', ownerId: 'germany', value: 8, supply: 72, terrain: '항구 도시', neighbors: ['france', 'brittany', 'spain', 'atlantic'], theater: 'europe', siteType: 'port', frontId: 'occupied-france', labelTier: 2 }),
  site({ id: 'murmansk', name: '무르만스크', region: '소련 북극권', px: 616, py: 132, controller: 'allies', ownerId: 'ussr', value: 10, supply: 69, terrain: '부동항', neighbors: ['narvik', 'finland', 'archangel', 'iceland'], theater: 'europe', siteType: 'port', frontId: 'arctic-supply', labelTier: 1 }),
  site({ id: 'archangel', name: '아르한겔스크', region: '소련 북극권', px: 766, py: 144, controller: 'allies', ownerId: 'ussr', value: 8, supply: 63, terrain: '항구 도시', neighbors: ['murmansk', 'moscow', 'leningrad'], theater: 'europe', siteType: 'port', frontId: 'arctic-supply', labelTier: 1 }),
  site({ id: 'cherbourg', name: '셰르부르·코탕탱', region: '노르망디', px: 349, py: 449, controller: 'axis', ownerId: 'germany', value: 9, supply: 78, terrain: '요새 항구', neighbors: ['channel', 'normandy', 'saint_lo', 'brittany'], theater: 'europe', siteType: 'fortress', frontId: 'cotentin-front', labelTier: 1 }),
  site({ id: 'saint_lo', name: '생로·보카주', region: '노르망디', px: 369, py: 461, controller: 'axis', ownerId: 'germany', value: 7, supply: 61, terrain: '구릉 도시', neighbors: ['cherbourg', 'normandy', 'france'], theater: 'europe', siteType: 'front', frontId: 'cotentin-front', labelTier: 2 }),
  site({ id: 'cologne', name: '쾰른·라인강', region: '라인란트', px: 476, py: 414, controller: 'axis', ownerId: 'germany', value: 11, supply: 91, terrain: '공업 도시', neighbors: ['ruhr', 'aachen', 'frankfurt', 'lowlands'], theater: 'europe', siteType: 'city', frontId: 'rhineland-front', labelTier: 1 }),
  site({ id: 'aachen', name: '아헨·서부방벽', region: '라인란트', px: 458, py: 421, controller: 'axis', ownerId: 'germany', value: 8, supply: 84, terrain: '요새 도시', neighbors: ['lowlands', 'cologne', 'france'], theater: 'europe', siteType: 'fortress', frontId: 'rhineland-front', labelTier: 2 }),
  site({ id: 'frankfurt', name: '프랑크푸르트암마인', region: '라인란트', px: 506, py: 435, controller: 'axis', ownerId: 'germany', value: 9, supply: 93, terrain: '도시', neighbors: ['cologne', 'ruhr', 'germany', 'munich'], theater: 'europe', siteType: 'city', frontId: 'rhineland-front', labelTier: 2 }),
  site({ id: 'rzhev', name: '르제프 돌출부', region: '모스크바 서방', px: 792, py: 351, controller: 'axis', ownerId: 'germany', value: 8, supply: 39, terrain: '삼림 요새', neighbors: ['smolensk', 'vyazma', 'moscow', 'leningrad'], theater: 'europe', siteType: 'front', frontId: 'rzhev-vyazma', labelTier: 1 }),
  site({ id: 'vyazma', name: '뱌지마', region: '모스크바 서방', px: 800, py: 383, controller: 'axis', ownerId: 'germany', value: 7, supply: 46, terrain: '철도 도시', neighbors: ['rzhev', 'smolensk', 'moscow', 'orel'], theater: 'europe', siteType: 'front', frontId: 'rzhev-vyazma', labelTier: 2 }),
  site({ id: 'kursk', name: '쿠르스크', region: '중부 동부전선', px: 803, py: 438, controller: 'axis', ownerId: 'germany', value: 10, supply: 52, terrain: '철도 도시', neighbors: ['orel', 'voronezh', 'kharkov', 'ukraine'], theater: 'europe', siteType: 'fortress', frontId: 'kursk-orel', labelTier: 1 }),
  site({ id: 'orel', name: '오룔', region: '중부 동부전선', px: 804, py: 410, controller: 'axis', ownerId: 'germany', value: 8, supply: 48, terrain: '도시 평야', neighbors: ['kursk', 'vyazma', 'smolensk', 'voronezh'], theater: 'europe', siteType: 'front', frontId: 'kursk-orel', labelTier: 2 }),
  site({ id: 'voronezh', name: '보로네시', region: '돈강 상류', px: 841, py: 445, controller: 'allies', ownerId: 'ussr', value: 9, supply: 56, terrain: '강변 도시', neighbors: ['kursk', 'orel', 'stalingrad', 'kharkov'], theater: 'europe', siteType: 'city', frontId: 'kursk-orel', labelTier: 1 }),
  site({ id: 'dnipropetrovsk', name: '드네프로페트롭스크', region: '우크라이나', px: 777, py: 500, controller: 'axis', ownerId: 'germany', value: 10, supply: 66, terrain: '강변 공업도시', neighbors: ['ukraine', 'kharkov', 'donetsk', 'nikolaev'], theater: 'europe', siteType: 'city', frontId: 'donbas-azov', labelTier: 1, historicalNote: '오늘날 드니프로의 1942년 당시 명칭' }),
  site({ id: 'donetsk', name: '스탈리노(오늘날 도네츠크)', region: '돈바스', px: 816, py: 508, controller: 'axis', ownerId: 'germany', value: 11, supply: 63, terrain: '광공업 도시', neighbors: ['dnipropetrovsk', 'kharkov', 'mariupol', 'rostov'], theater: 'europe', siteType: 'city', frontId: 'donbas-azov', labelTier: 1, historicalNote: '1924–1961년 사용된 당시 도시명 스탈리노' }),
  site({ id: 'mariupol', name: '마리우폴·아조프해', region: '돈바스 남부', px: 811, py: 535, controller: 'axis', ownerId: 'germany', value: 8, supply: 54, terrain: '항구 도시', neighbors: ['donetsk', 'rostov', 'crimea', 'nikolaev'], theater: 'europe', siteType: 'port', frontId: 'donbas-azov', labelTier: 2 }),
  site({ id: 'odessa', name: '오데사', region: '흑해 북안', px: 716, py: 554, controller: 'axis', ownerId: 'germany', value: 9, supply: 62, terrain: '요새 항구', neighbors: ['ukraine', 'nikolaev', 'crimea', 'bucharest'], theater: 'europe', siteType: 'fortress', frontId: 'black-sea-coast', labelTier: 1 }),
  site({ id: 'nikolaev', name: '니콜라예프 조선소', region: '흑해 북안', px: 746, py: 535, controller: 'axis', ownerId: 'germany', value: 9, supply: 59, terrain: '항구 공업도시', neighbors: ['odessa', 'dnipropetrovsk', 'mariupol', 'crimea'], theater: 'europe', siteType: 'port', frontId: 'black-sea-coast', labelTier: 2 }),
  site({ id: 'maikop', name: '마이코프 유전', region: '북캅카스', px: 842, py: 568, controller: 'axis', ownerId: 'germany', value: 11, supply: 43, terrain: '산악 유전', neighbors: ['rostov', 'caucasus', 'grozny'], theater: 'europe', siteType: 'front', frontId: 'kuban-caucasus', labelTier: 1 }),
  site({ id: 'grozny', name: '그로즈니 유전', region: '북캅카스', px: 884, py: 581, controller: 'allies', ownerId: 'ussr', value: 12, supply: 55, terrain: '산악 공업도시', neighbors: ['maikop', 'caucasus', 'baku', 'stalingrad'], theater: 'europe', siteType: 'city', frontId: 'kuban-caucasus', labelTier: 1 }),
  site({ id: 'zagreb', name: '자그레브', region: '유고슬라비아', px: 592, py: 545, controller: 'axis', ownerId: 'germany', value: 7, supply: 58, terrain: '도시 구릉', neighbors: ['alps', 'balkans', 'sarajevo', 'belgrade'], theater: 'europe', siteType: 'city', frontId: 'adriatic-partisan', labelTier: 2 }),
  site({ id: 'sarajevo', name: '사라예보·보스니아 산악구', region: '유고슬라비아', px: 616, py: 574, controller: 'axis', ownerId: 'germany', value: 7, supply: 41, terrain: '산악 도시', neighbors: ['zagreb', 'belgrade', 'balkans', 'greece'], theater: 'europe', siteType: 'front', frontId: 'adriatic-partisan', labelTier: 1 }),
  site({ id: 'messina', name: '메시나 해협', region: '시칠리아', px: 579, py: 642, controller: 'axis', ownerId: 'italy', value: 8, supply: 67, terrain: '요새 항구', neighbors: ['sicily', 'malta', 'taranto', 'salerno'], theater: 'europe', siteType: 'fortress', frontId: 'sicily-calabria', labelTier: 1 }),
  site({ id: 'taranto', name: '타란토 해군기지', region: '남이탈리아', px: 604, py: 608, controller: 'axis', ownerId: 'italy', value: 9, supply: 78, terrain: '해군기지', neighbors: ['messina', 'naples', 'greece', 'italy'], theater: 'europe', siteType: 'port', frontId: 'sicily-calabria', labelTier: 1 }),
  site({ id: 'damascus', name: '다마스쿠스', region: '프랑스령 시리아', px: 876, py: 660, controller: 'allies', ownerId: 'freefrance', value: 8, supply: 72, terrain: '내륙 도시', neighbors: ['beirut', 'levant', 'jerusalem', 'baghdad'], theater: 'europe', siteType: 'city', frontId: 'levant-iraq', labelTier: 1 }),
  site({ id: 'jerusalem', name: '예루살렘·팔레스타인 위임통치령', region: '팔레스타인', px: 867, py: 686, controller: 'allies', ownerId: 'britain', value: 8, supply: 76, terrain: '구릉 도시', neighbors: ['damascus', 'suez', 'cairo', 'baghdad'], theater: 'europe', siteType: 'city', frontId: 'levant-iraq', labelTier: 2 }),
  site({ id: 'basra', name: '바스라·샤트알아랍', region: '이라크', px: 1022, py: 700, controller: 'allies', ownerId: 'britain', value: 9, supply: 81, terrain: '항구 도시', neighbors: ['baghdad', 'tehran', 'jerusalem'], theater: 'europe', siteType: 'port', frontId: 'levant-iraq', labelTier: 1 }),

  // Asia, China, the Indian Ocean and the Pacific
  site({ id: 'bombay', name: '봄베이 항구', region: '인도 병참기지', px: 212, py: 438, controller: 'allies', ownerId: 'india', value: 9, supply: 92, terrain: '항구 도시', neighbors: ['india', 'madras', 'ceylon'], theater: 'asia', siteType: 'port', frontId: 'india-base', labelTier: 1 }),
  site({ id: 'madras', name: '마드라스', region: '인도 병참기지', px: 259, py: 477, controller: 'allies', ownerId: 'india', value: 7, supply: 86, terrain: '항구 도시', neighbors: ['india', 'bombay', 'calcutta', 'ceylon'], theater: 'asia', siteType: 'port', frontId: 'india-base', labelTier: 2 }),
  site({ id: 'calcutta', name: '캘커타', region: '인도 동부 병참', px: 333, py: 420, controller: 'allies', ownerId: 'india', value: 11, supply: 94, terrain: '항구 도시', neighbors: ['india', 'madras', 'assam', 'imphal', 'arakan'], theater: 'asia', siteType: 'port', frontId: 'india-base', labelTier: 1 }),
  site({ id: 'kohima', name: '코히마', region: '인도-버마 국경', px: 390, py: 386, controller: 'allies', ownerId: 'india', value: 7, supply: 48, terrain: '산악 요새', neighbors: ['assam', 'imphal', 'myitkyina'], theater: 'asia', siteType: 'fortress', frontId: 'imphal-kohima', labelTier: 1 }),
  site({ id: 'imphal', name: '임팔', region: '인도-버마 국경', px: 398, py: 414, controller: 'allies', ownerId: 'india', value: 8, supply: 51, terrain: '산악 도시', neighbors: ['assam', 'kohima', 'calcutta', 'chindwin', 'arakan'], theater: 'asia', siteType: 'fortress', frontId: 'imphal-kohima', labelTier: 1 }),
  site({ id: 'arakan', name: '아라칸·아키아브', region: '버마 서부', px: 407, py: 465, controller: 'axis', ownerId: 'japan', value: 7, supply: 38, terrain: '정글 해안', neighbors: ['calcutta', 'imphal', 'burma', 'chindwin'], theater: 'asia', siteType: 'front', frontId: 'arakan-front', labelTier: 1 }),
  site({ id: 'myitkyina', name: '미치나', region: '북부 버마', px: 435, py: 385, controller: 'axis', ownerId: 'japan', value: 8, supply: 36, terrain: '정글 비행장', neighbors: ['assam', 'kohima', 'chindwin', 'lashio', 'yunnan'], theater: 'asia', siteType: 'front', frontId: 'north-burma', labelTier: 1 }),
  site({ id: 'lashio', name: '라시오·버마로드', region: '북부 버마', px: 455, py: 418, controller: 'axis', ownerId: 'japan', value: 8, supply: 43, terrain: '산악 도시', neighbors: ['myitkyina', 'mandalay', 'yunnan', 'burma'], theater: 'asia', siteType: 'city', frontId: 'north-burma', labelTier: 1 }),
  site({ id: 'chindwin', name: '친드윈 강 방면', region: '중부 버마', px: 423, py: 432, controller: 'axis', ownerId: 'japan', value: 6, supply: 31, terrain: '강변 정글', neighbors: ['imphal', 'arakan', 'myitkyina', 'mandalay'], theater: 'asia', siteType: 'front', frontId: 'chindwin-burma', labelTier: 2 }),
  site({ id: 'mandalay', name: '만달레이·이라와디', region: '중부 버마', px: 448, py: 449, controller: 'axis', ownerId: 'japan', value: 9, supply: 49, terrain: '강변 도시', neighbors: ['chindwin', 'lashio', 'burma', 'myitkyina'], theater: 'asia', siteType: 'city', frontId: 'chindwin-burma', labelTier: 1 }),
  site({ id: 'saigon', name: '사이공·코친차이나', region: '인도차이나', px: 540, py: 525, controller: 'axis', ownerId: 'japan', value: 9, supply: 75, terrain: '항구 도시', neighbors: ['indochina', 'malaya', 'south_china', 'dutch_east_indies'], theater: 'asia', siteType: 'port', frontId: 'indochina-front', labelTier: 1 }),
  site({ id: 'shanghai', name: '상하이', region: '중국 동부', px: 650, py: 372, controller: 'axis', ownerId: 'japan', value: 12, supply: 91, terrain: '항구 도시', neighbors: ['north_china', 'nanjing', 'central_china', 'taiwan'], theater: 'asia', siteType: 'port', frontId: 'lower-yangtze', labelTier: 1 }),
  site({ id: 'nanjing', name: '난징', region: '중국 동부', px: 626, py: 387, controller: 'axis', ownerId: 'japan', value: 10, supply: 82, terrain: '강변 도시', neighbors: ['shanghai', 'central_china', 'shandong', 'changsha'], theater: 'asia', siteType: 'city', frontId: 'lower-yangtze', labelTier: 1 }),
  site({ id: 'shandong', name: '지난·산둥', region: '화북', px: 628, py: 331, controller: 'axis', ownerId: 'japan', value: 8, supply: 69, terrain: '평야 도시', neighbors: ['north_china', 'nanjing', 'manchuria', 'xian'], theater: 'asia', siteType: 'front', frontId: 'north-china', labelTier: 2 }),
  site({ id: 'xian', name: '시안·황허 후방', region: '중국 내륙', px: 553, py: 327, controller: 'allies', ownerId: 'china', value: 8, supply: 52, terrain: '고원 도시', neighbors: ['china_interior', 'north_china', 'shandong', 'central_china'], theater: 'asia', siteType: 'city', frontId: 'north-china', labelTier: 1 }),
  site({ id: 'changsha', name: '창사', region: '화중', px: 589, py: 411, controller: 'allies', ownerId: 'china', value: 9, supply: 53, terrain: '강변 도시', neighbors: ['central_china', 'nanjing', 'hengyang', 'china_interior'], theater: 'asia', siteType: 'fortress', frontId: 'central-china', labelTier: 1 }),
  site({ id: 'hengyang', name: '헝양', region: '화남', px: 582, py: 438, controller: 'allies', ownerId: 'china', value: 8, supply: 45, terrain: '도시 구릉', neighbors: ['changsha', 'guilin', 'south_china'], theater: 'asia', siteType: 'front', frontId: 'south-china', labelTier: 1 }),
  site({ id: 'guilin', name: '구이린', region: '화남', px: 557, py: 458, controller: 'allies', ownerId: 'china', value: 7, supply: 42, terrain: '산악 도시', neighbors: ['hengyang', 'south_china', 'yunnan', 'indochina'], theater: 'asia', siteType: 'front', frontId: 'south-china', labelTier: 2 }),
  site({ id: 'hong_kong', name: '홍콩', region: '화남 해안', px: 611, py: 464, controller: 'axis', ownerId: 'japan', value: 9, supply: 79, terrain: '요새 항구', neighbors: ['south_china', 'taiwan', 'indochina', 'philippines'], theater: 'asia', siteType: 'port', frontId: 'south-china', labelTier: 1 }),
  site({ id: 'taiwan', name: '다이호쿠(타이베이)·대만', region: '동중국해', px: 674, py: 430, controller: 'axis', ownerId: 'japan', value: 10, supply: 88, terrain: '도서 기지', neighbors: ['shanghai', 'hong_kong', 'japan_home', 'philippines', 'okinawa'], theater: 'asia', siteType: 'island', frontId: 'japan-home', labelTier: 1, historicalNote: '일본 통치기 타이베이의 당시 행정명 다이호쿠를 병기' }),
  site({ id: 'harbin', name: '하얼빈·북만주', region: '만주', px: 704, py: 198, controller: 'axis', ownerId: 'japan', value: 8, supply: 78, terrain: '철도 도시', neighbors: ['manchuria', 'soviet_far_east', 'korea', 'mongolia'], theater: 'asia', siteType: 'city', frontId: 'manchuria-korea', labelTier: 1 }),
  site({ id: 'busan', name: '부산부·진해 군항', region: '조선', px: 748, py: 322, controller: 'axis', ownerId: 'japan', value: 9, supply: 88, terrain: '항구 도시', neighbors: ['korea', 'manchuria', 'japan_home'], theater: 'asia', siteType: 'port', frontId: 'korea-liberation', labelTier: 1 }),
  site({ id: 'osaka_kure', name: '오사카·구레 군항', region: '일본 본토', px: 780, py: 345, controller: 'axis', ownerId: 'japan', value: 12, supply: 98, terrain: '공업 항구', neighbors: ['japan_home', 'busan', 'okinawa', 'saipan'], theater: 'asia', siteType: 'port', frontId: 'japan-home', labelTier: 1 }),
  site({ id: 'hokkaido', name: '삿포로·홋카이도', region: '일본 본토', px: 830, py: 277, controller: 'axis', ownerId: 'japan', value: 7, supply: 81, terrain: '도서 산악', neighbors: ['japan_home', 'soviet_far_east', 'attu'], theater: 'asia', siteType: 'island', frontId: 'north-pacific', labelTier: 2 }),
  site({ id: 'okinawa', name: '오키나와·류큐', region: '류큐 제도', px: 752, py: 420, controller: 'axis', ownerId: 'japan', value: 10, supply: 75, terrain: '요새 도서', neighbors: ['japan_home', 'osaka_kure', 'taiwan', 'saipan', 'philippines'], theater: 'asia', siteType: 'fortress', frontId: 'ryukyu-okinawa', labelTier: 1 }),
  site({ id: 'bataan', name: '바탄·코레히도르', region: '루손', px: 674, py: 501, controller: 'axis', ownerId: 'japan', value: 8, supply: 47, terrain: '요새 해안', neighbors: ['philippines', 'taiwan', 'leyte'], theater: 'asia', siteType: 'fortress', frontId: 'philippines', labelTier: 1 }),
  site({ id: 'leyte', name: '레이테·사마르', region: '필리핀 중부', px: 700, py: 548, controller: 'axis', ownerId: 'japan', value: 8, supply: 54, terrain: '도서 정글', neighbors: ['philippines', 'bataan', 'mindanao', 'palau'], theater: 'asia', siteType: 'island', frontId: 'philippines', labelTier: 1 }),
  site({ id: 'mindanao', name: '민다나오·다바오', region: '필리핀 남부', px: 690, py: 584, controller: 'axis', ownerId: 'japan', value: 8, supply: 57, terrain: '도서 정글', neighbors: ['philippines', 'leyte', 'borneo', 'new_guinea'], theater: 'asia', siteType: 'island', frontId: 'philippines', labelTier: 1 }),
  site({ id: 'sumatra', name: '팔렘방·수마트라', region: '네덜란드령 동인도', px: 527, py: 620, controller: 'axis', ownerId: 'japan', value: 11, supply: 72, terrain: '도서 정글', neighbors: ['malaya', 'singapore', 'dutch_east_indies', 'borneo'], theater: 'asia', siteType: 'island', frontId: 'east-indies', labelTier: 1 }),
  site({ id: 'borneo', name: '보르네오·발릭파판', region: '네덜란드령 동인도', px: 623, py: 606, controller: 'axis', ownerId: 'japan', value: 11, supply: 68, terrain: '도서 정글', neighbors: ['sumatra', 'dutch_east_indies', 'celebes', 'mindanao'], theater: 'asia', siteType: 'island', frontId: 'east-indies', labelTier: 1 }),
  site({ id: 'celebes', name: '마카사르·셀레베스', region: '네덜란드령 동인도', px: 686, py: 635, controller: 'axis', ownerId: 'japan', value: 8, supply: 59, terrain: '도서 정글', neighbors: ['borneo', 'dutch_east_indies', 'timor', 'new_guinea'], theater: 'asia', siteType: 'island', frontId: 'east-indies', labelTier: 2 }),
  site({ id: 'timor', name: '티모르', region: '네덜란드령 동인도', px: 691, py: 691, controller: 'axis', ownerId: 'japan', value: 6, supply: 37, terrain: '도서 산악', neighbors: ['dutch_east_indies', 'celebes', 'darwin'], theater: 'asia', siteType: 'island', frontId: 'east-indies', labelTier: 2 }),
  site({ id: 'port_moresby', name: '포트모르즈비', region: '파푸아', px: 865, py: 670, controller: 'allies', ownerId: 'britain', value: 10, supply: 61, terrain: '항구 정글', neighbors: ['new_guinea', 'lae', 'coral_sea', 'darwin', 'brisbane'], theater: 'asia', siteType: 'port', frontId: 'papua', labelTier: 1 }),
  site({ id: 'lae', name: '라에·살라마우아', region: '뉴기니', px: 851, py: 628, controller: 'axis', ownerId: 'japan', value: 8, supply: 42, terrain: '비행장 정글', neighbors: ['new_guinea', 'port_moresby', 'hollandia', 'rabaul'], theater: 'asia', siteType: 'front', frontId: 'new-guinea', labelTier: 1 }),
  site({ id: 'hollandia', name: '홀란디아·아이타페', region: '뉴기니 북안', px: 798, py: 627, controller: 'axis', ownerId: 'japan', value: 8, supply: 45, terrain: '항구 정글', neighbors: ['dutch_east_indies', 'new_guinea', 'lae', 'palau'], theater: 'asia', siteType: 'port', frontId: 'new-guinea', labelTier: 1 }),
  site({ id: 'rabaul', name: '라바울·뉴브리튼', region: '비스마르크 제도', px: 925, py: 600, controller: 'axis', ownerId: 'japan', value: 11, supply: 79, terrain: '요새 항구', neighbors: ['lae', 'new_guinea', 'solomons', 'bougainville', 'truk'], theater: 'asia', siteType: 'fortress', frontId: 'solomons', labelTier: 1 }),
  site({ id: 'bougainville', name: '부건빌', region: '북부 솔로몬', px: 981, py: 614, controller: 'axis', ownerId: 'japan', value: 7, supply: 47, terrain: '도서 정글', neighbors: ['solomons', 'rabaul', 'truk'], theater: 'asia', siteType: 'island', frontId: 'solomons', labelTier: 1 }),
  site({ id: 'guam', name: '괌', region: '마리아나 제도', px: 902, py: 476, controller: 'axis', ownerId: 'japan', value: 8, supply: 61, terrain: '요새 도서', neighbors: ['saipan', 'palau', 'truk', 'midway'], theater: 'asia', siteType: 'island', frontId: 'central-pacific', labelTier: 1 }),
  site({ id: 'saipan', name: '사이판·티니안', region: '마리아나 제도', px: 916, py: 447, controller: 'axis', ownerId: 'japan', value: 10, supply: 71, terrain: '요새 도서', neighbors: ['osaka_kure', 'okinawa', 'guam', 'truk', 'midway'], theater: 'asia', siteType: 'island', frontId: 'central-pacific', labelTier: 1 }),
  site({ id: 'truk', name: '트루크 환초', region: '캐롤라인 제도', px: 955, py: 536, controller: 'axis', ownerId: 'japan', value: 11, supply: 82, terrain: '해군기지', neighbors: ['saipan', 'guam', 'palau', 'rabaul', 'bougainville', 'marshalls'], theater: 'asia', siteType: 'port', frontId: 'central-pacific', labelTier: 1 }),
  site({ id: 'palau', name: '팔라우·펠렐리우', region: '서부 캐롤라인', px: 823, py: 553, controller: 'axis', ownerId: 'japan', value: 8, supply: 58, terrain: '요새 도서', neighbors: ['philippines', 'leyte', 'hollandia', 'guam', 'truk'], theater: 'asia', siteType: 'fortress', frontId: 'central-pacific', labelTier: 1 }),
  site({ id: 'marshalls', name: '마셜 제도·콰잘레인', region: '동부 위임통치령', px: 1032, py: 526, controller: 'axis', ownerId: 'japan', value: 8, supply: 58, terrain: '요새 도서', neighbors: ['truk', 'midway', 'hawaii', 'solomons'], theater: 'asia', siteType: 'island', frontId: 'central-pacific', labelTier: 1 }),
  site({ id: 'attu', name: '애투·알류샨', region: '북태평양', px: 1000, py: 260, controller: 'axis', ownerId: 'japan', value: 6, supply: 28, terrain: '도서 산악', neighbors: ['hokkaido', 'midway', 'hawaii'], theater: 'asia', siteType: 'island', frontId: 'north-pacific', labelTier: 1 }),
  site({ id: 'darwin', name: '다윈', region: '호주 북부', px: 724, py: 730, controller: 'allies', ownerId: 'britain', value: 8, supply: 77, terrain: '항구 도시', neighbors: ['timor', 'port_moresby', 'brisbane'], theater: 'asia', siteType: 'port', frontId: 'southwest-pacific', labelTier: 1 }),
  site({ id: 'brisbane', name: '브리즈번·연합군 사령부', region: '호주 동부', px: 917, py: 733, controller: 'allies', ownerId: 'britain', value: 10, supply: 96, terrain: '항구 도시', neighbors: ['darwin', 'port_moresby', 'coral_sea', 'solomons'], theater: 'asia', siteType: 'port', frontId: 'southwest-pacific', labelTier: 1 }),
  site({ id: 'karachi', name: '카라치 항구', region: '인도 병참기지', px: 154, py: 407, controller: 'allies', ownerId: 'india', value: 9, supply: 91, terrain: '항구 도시', neighbors: ['india', 'bombay', 'ceylon'], theater: 'asia', siteType: 'port', frontId: 'india-base', labelTier: 1 }),
  site({ id: 'chittagong', name: '치타공', region: '벵골만', px: 367, py: 445, controller: 'allies', ownerId: 'india', value: 9, supply: 77, terrain: '항구 정글', neighbors: ['calcutta', 'arakan', 'dimapur', 'imphal'], theater: 'asia', siteType: 'port', frontId: 'bengal-assam', labelTier: 1 }),
  site({ id: 'dimapur', name: '디마푸르 철도종점', region: '아삼', px: 382, py: 398, controller: 'allies', ownerId: 'india', value: 8, supply: 64, terrain: '철도 도시', neighbors: ['assam', 'kohima', 'imphal', 'chittagong'], theater: 'asia', siteType: 'city', frontId: 'bengal-assam', labelTier: 1 }),
  site({ id: 'meiktila', name: '메이크틸라', region: '중부 버마', px: 449, py: 463, controller: 'axis', ownerId: 'japan', value: 8, supply: 45, terrain: '비행장 평야', neighbors: ['mandalay', 'burma', 'pegu', 'chindwin'], theater: 'asia', siteType: 'front', frontId: 'irrawaddy-front', labelTier: 1 }),
  site({ id: 'pegu', name: '페구·이라와디 삼각주', region: '남부 버마', px: 445, py: 487, controller: 'axis', ownerId: 'japan', value: 7, supply: 51, terrain: '강변 정글', neighbors: ['meiktila', 'burma', 'arakan', 'bangkok'], theater: 'asia', siteType: 'front', frontId: 'irrawaddy-front', labelTier: 2 }),
  site({ id: 'bangkok', name: '방콕·타이 왕국', region: '태국', px: 500, py: 511, controller: 'axis', ownerId: 'japan', value: 10, supply: 83, terrain: '강변 도시', neighbors: ['pegu', 'indochina', 'malaya', 'penang'], theater: 'asia', siteType: 'capital', frontId: 'thailand-malaya', labelTier: 1 }),
  site({ id: 'penang', name: '페낭·조지타운', region: '영국령 말라야', px: 476, py: 552, controller: 'axis', ownerId: 'japan', value: 8, supply: 71, terrain: '항구 도시', neighbors: ['bangkok', 'malaya', 'singapore', 'sumatra'], theater: 'asia', siteType: 'port', frontId: 'thailand-malaya', labelTier: 1 }),
  site({ id: 'haiphong', name: '하이퐁', region: '프랑스령 인도차이나', px: 538, py: 472, controller: 'axis', ownerId: 'japan', value: 9, supply: 77, terrain: '항구 도시', neighbors: ['indochina', 'south_china', 'saigon', 'yunnan'], theater: 'asia', siteType: 'port', frontId: 'indochina-front', labelTier: 1 }),
  site({ id: 'tianjin', name: '톈진·대고구', region: '화북', px: 620, py: 309, controller: 'axis', ownerId: 'japan', value: 9, supply: 82, terrain: '항구 도시', neighbors: ['north_china', 'shandong', 'taiyuan', 'manchuria'], theater: 'asia', siteType: 'port', frontId: 'yellow-river', labelTier: 1 }),
  site({ id: 'taiyuan', name: '타이위안·산시', region: '화북', px: 588, py: 309, controller: 'axis', ownerId: 'japan', value: 8, supply: 57, terrain: '산악 도시', neighbors: ['north_china', 'tianjin', 'xian', 'zhengzhou'], theater: 'asia', siteType: 'front', frontId: 'yellow-river', labelTier: 1 }),
  site({ id: 'zhengzhou', name: '정저우·황허 교차점', region: '중원', px: 602, py: 345, controller: 'axis', ownerId: 'japan', value: 9, supply: 59, terrain: '철도 도시', neighbors: ['taiyuan', 'xian', 'shandong', 'nanchang', 'central_china'], theater: 'asia', siteType: 'city', frontId: 'yellow-river', labelTier: 1 }),
  site({ id: 'nanchang', name: '난창', region: '화중', px: 617, py: 403, controller: 'axis', ownerId: 'japan', value: 8, supply: 58, terrain: '강변 도시', neighbors: ['central_china', 'zhengzhou', 'changde', 'nanjing', 'changsha'], theater: 'asia', siteType: 'front', frontId: 'wuhan-nanchang', labelTier: 1 }),
  site({ id: 'changde', name: '창더', region: '후난', px: 577, py: 395, controller: 'allies', ownerId: 'china', value: 8, supply: 46, terrain: '강변 도시', neighbors: ['central_china', 'nanchang', 'changsha', 'china_interior'], theater: 'asia', siteType: 'fortress', frontId: 'wuhan-nanchang', labelTier: 1 }),
  site({ id: 'xinjing', name: '신징(新京)·만주국 수도', region: '만주국', px: 690, py: 220, controller: 'axis', ownerId: 'japan', value: 10, supply: 89, terrain: '철도 도시', neighbors: ['manchuria', 'harbin', 'dalian', 'sinuiju'], theater: 'asia', siteType: 'capital', frontId: 'south-manchuria-korea', labelTier: 1, historicalNote: '오늘날 창춘의 만주국 시기 명칭' }),
  site({ id: 'dalian', name: '다이렌·관동주', region: '남만주', px: 697, py: 275, controller: 'axis', ownerId: 'japan', value: 10, supply: 91, terrain: '항구 도시', neighbors: ['manchuria', 'xinjing', 'sinuiju', 'busan'], theater: 'asia', siteType: 'port', frontId: 'south-manchuria-korea', labelTier: 1, historicalNote: '오늘날 다롄의 일본 관동주 시기 명칭' }),
  site({ id: 'sinuiju', name: '신의주·압록강 철교', region: '조선 북부', px: 708, py: 267, controller: 'axis', ownerId: 'japan', value: 8, supply: 83, terrain: '철도 도시', neighbors: ['dalian', 'xinjing', 'pyongyang', 'korea'], theater: 'asia', siteType: 'city', frontId: 'south-manchuria-korea', labelTier: 1 }),
  site({ id: 'pyongyang', name: '평양부', region: '조선 북부', px: 719, py: 287, controller: 'axis', ownerId: 'japan', value: 8, supply: 81, terrain: '강변 도시', neighbors: ['sinuiju', 'korea', 'busan', 'dalian'], theater: 'asia', siteType: 'city', frontId: 'korea-liberation', labelTier: 1 }),
  site({ id: 'nagoya', name: '나고야 항공공업지대', region: '일본 본토', px: 797, py: 337, controller: 'axis', ownerId: 'japan', value: 12, supply: 97, terrain: '공업 도시', neighbors: ['japan_home', 'osaka_kure', 'yokosuka', 'hiroshima'], theater: 'asia', siteType: 'city', frontId: 'home-islands-industry', labelTier: 1 }),
  site({ id: 'yokosuka', name: '요코스카 군항', region: '일본 본토', px: 818, py: 343, controller: 'axis', ownerId: 'japan', value: 12, supply: 98, terrain: '해군기지', neighbors: ['japan_home', 'nagoya', 'iwo_jima', 'hokkaido'], theater: 'asia', siteType: 'port', frontId: 'home-islands-industry', labelTier: 1 }),
  site({ id: 'hiroshima', name: '히로시마·구레 공업축', region: '일본 본토', px: 770, py: 351, controller: 'axis', ownerId: 'japan', value: 11, supply: 96, terrain: '공업 항구', neighbors: ['osaka_kure', 'nagoya', 'sasebo', 'busan'], theater: 'asia', siteType: 'city', frontId: 'home-islands-industry', labelTier: 1 }),
  site({ id: 'sasebo', name: '사세보 군항', region: '일본 본토', px: 750, py: 350, controller: 'axis', ownerId: 'japan', value: 10, supply: 94, terrain: '해군기지', neighbors: ['hiroshima', 'busan', 'okinawa'], theater: 'asia', siteType: 'port', frontId: 'home-islands-industry', labelTier: 2 }),
  site({ id: 'lingayen', name: '링가옌만', region: '루손', px: 669, py: 481, controller: 'axis', ownerId: 'japan', value: 8, supply: 59, terrain: '상륙 해안', neighbors: ['philippines', 'clark', 'bataan', 'taiwan'], theater: 'asia', siteType: 'front', frontId: 'luzon-front', labelTier: 1 }),
  site({ id: 'clark', name: '클라크 비행장', region: '루손', px: 676, py: 492, controller: 'axis', ownerId: 'japan', value: 9, supply: 65, terrain: '비행장 평야', neighbors: ['lingayen', 'philippines', 'bataan'], theater: 'asia', siteType: 'fortress', frontId: 'luzon-front', labelTier: 1 }),
  site({ id: 'cebu', name: '세부', region: '비사야 제도', px: 700, py: 535, controller: 'axis', ownerId: 'japan', value: 8, supply: 60, terrain: '항구 도시', neighbors: ['leyte', 'philippines', 'davao', 'mindanao'], theater: 'asia', siteType: 'port', frontId: 'philippine-resistance', labelTier: 1 }),
  site({ id: 'davao', name: '다바오', region: '민다나오', px: 700, py: 575, controller: 'axis', ownerId: 'japan', value: 8, supply: 67, terrain: '항구 정글', neighbors: ['cebu', 'mindanao', 'borneo', 'palau'], theater: 'asia', siteType: 'port', frontId: 'visayas-mindanao', labelTier: 1 }),
  site({ id: 'kavieng', name: '캐비엥·뉴아일랜드', region: '비스마르크 제도', px: 923, py: 579, controller: 'axis', ownerId: 'japan', value: 8, supply: 64, terrain: '요새 항구', neighbors: ['rabaul', 'admiralties', 'truk', 'bougainville'], theater: 'asia', siteType: 'port', frontId: 'bismarck-archipelago', labelTier: 1 }),
  site({ id: 'admiralties', name: '애드미럴티 제도·마누스', region: '비스마르크 제도', px: 878, py: 593, controller: 'axis', ownerId: 'japan', value: 8, supply: 52, terrain: '도서 기지', neighbors: ['kavieng', 'hollandia', 'rabaul', 'new_guinea'], theater: 'asia', siteType: 'island', frontId: 'bismarck-archipelago', labelTier: 1 }),
  site({ id: 'kwajalein', name: '콰잘레인 환초', region: '마셜 제도', px: 1029, py: 519, controller: 'axis', ownerId: 'japan', value: 9, supply: 61, terrain: '요새 도서', neighbors: ['marshalls', 'eniwetok', 'tarawa', 'truk'], theater: 'asia', siteType: 'fortress', frontId: 'eastern-mandates', labelTier: 1 }),
  site({ id: 'eniwetok', name: '에니웨톡 환초', region: '마셜 제도', px: 1015, py: 490, controller: 'axis', ownerId: 'japan', value: 8, supply: 54, terrain: '요새 도서', neighbors: ['kwajalein', 'marshalls', 'wake', 'saipan'], theater: 'asia', siteType: 'island', frontId: 'eastern-mandates', labelTier: 1 }),
  site({ id: 'tarawa', name: '타라와·베티오', region: '길버트 제도', px: 1052, py: 568, controller: 'axis', ownerId: 'japan', value: 9, supply: 50, terrain: '요새 도서', neighbors: ['makin', 'kwajalein', 'marshalls', 'solomons'], theater: 'asia', siteType: 'fortress', frontId: 'gilbert-islands', labelTier: 1 }),
  site({ id: 'makin', name: '마킨 환초', region: '길버트 제도', px: 1043, py: 551, controller: 'axis', ownerId: 'japan', value: 7, supply: 45, terrain: '도서 기지', neighbors: ['tarawa', 'kwajalein', 'marshalls'], theater: 'asia', siteType: 'island', frontId: 'gilbert-islands', labelTier: 2 }),
  site({ id: 'kiska', name: '키스카·알류샨', region: '알류샨 열도', px: 1047, py: 251, controller: 'axis', ownerId: 'japan', value: 7, supply: 27, terrain: '도서 산악', neighbors: ['attu', 'dutch_harbor', 'hokkaido'], theater: 'asia', siteType: 'island', frontId: 'aleutian-chain', labelTier: 1 }),
  site({ id: 'dutch_harbor', name: '더치하버·우날래스카', region: '알류샨 열도', px: 1092, py: 241, controller: 'allies', ownerId: 'usa', value: 8, supply: 72, terrain: '해군기지', neighbors: ['kiska', 'attu', 'hawaii'], theater: 'asia', siteType: 'port', frontId: 'aleutian-chain', labelTier: 1 }),
  site({ id: 'surabaya', name: '수라바야 해군기지', region: '네덜란드령 동인도', px: 616, py: 657, controller: 'axis', ownerId: 'japan', value: 10, supply: 76, terrain: '해군기지', neighbors: ['dutch_east_indies', 'sumatra', 'borneo', 'ambon'], theater: 'asia', siteType: 'port', frontId: 'east-indies', labelTier: 1 }),
  site({ id: 'ambon', name: '암본', region: '몰루카 제도', px: 727, py: 638, controller: 'axis', ownerId: 'japan', value: 8, supply: 48, terrain: '도서 기지', neighbors: ['celebes', 'surabaya', 'biak', 'timor'], theater: 'asia', siteType: 'island', frontId: 'east-indies', labelTier: 2 }),
  site({ id: 'biak', name: '비악 비행장', region: '뉴기니 북안', px: 814, py: 610, controller: 'axis', ownerId: 'japan', value: 9, supply: 43, terrain: '도서 비행장', neighbors: ['hollandia', 'new_guinea', 'ambon', 'admiralties'], theater: 'asia', siteType: 'fortress', frontId: 'new-guinea', labelTier: 1 }),
  site({ id: 'milne_bay', name: '밀른만', region: '파푸아', px: 898, py: 684, controller: 'allies', ownerId: 'britain', value: 8, supply: 56, terrain: '정글 해안', neighbors: ['port_moresby', 'new_guinea', 'coral_sea', 'rabaul'], theater: 'asia', siteType: 'front', frontId: 'papua', labelTier: 1 }),
  site({ id: 'tulagi', name: '툴라기·플로리다 제도', region: '솔로몬 제도', px: 1023, py: 630, controller: 'axis', ownerId: 'japan', value: 8, supply: 45, terrain: '도서 기지', neighbors: ['solomons', 'bougainville', 'rabaul', 'tarawa'], theater: 'asia', siteType: 'island', frontId: 'solomons', labelTier: 1 }),
  site({ id: 'wake', name: '웨이크 환초', region: '중부태평양', px: 1000, py: 427, controller: 'axis', ownerId: 'japan', value: 8, supply: 42, terrain: '요새 도서', neighbors: ['midway', 'eniwetok', 'marshalls', 'hawaii'], theater: 'asia', siteType: 'fortress', frontId: 'central-pacific', labelTier: 1 }),
  site({ id: 'iwo_jima', name: '이오지마', region: '오가사와라 제도', px: 862, py: 400, controller: 'axis', ownerId: 'japan', value: 9, supply: 65, terrain: '요새 도서', neighbors: ['japan_home', 'yokosuka', 'saipan', 'guam'], theater: 'asia', siteType: 'fortress', frontId: 'central-pacific', labelTier: 1 }),
  site({ id: 'townsville', name: '타운즈빌 병참기지', region: '호주 북동부', px: 890, py: 708, controller: 'allies', ownerId: 'britain', value: 9, supply: 91, terrain: '항구 도시', neighbors: ['brisbane', 'port_moresby', 'coral_sea', 'darwin'], theater: 'asia', siteType: 'port', frontId: 'southwest-pacific', labelTier: 1 }),
];

export const expandedHistoricalMapPoints = expandedPoints;

export function buildStrategicTerritories(base: Territory[]): Territory[] {
  const combined = [
    ...base.map((territory) => ({ ...territory, ...(baseEnhancements[territory.id] ?? {}) })),
    ...expandedTerritories,
  ];
  const byId = new Map(combined.map((territory) => [territory.id, territory]));
  const neighborSets = new Map(combined.map((territory) => [territory.id, new Set(territory.neighbors)]));

  combined.forEach((territory) => {
    territory.neighbors.forEach((neighborId) => {
      if (!byId.has(neighborId)) return;
      neighborSets.get(neighborId)?.add(territory.id);
    });
  });

  return combined.map((territory) => ({
    ...territory,
    neighbors: [...(neighborSets.get(territory.id) ?? [])].filter((id) => byId.has(id)).sort(),
  }));
}
